// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/headers/http/config.proto

package cloud.paolu.xray.transport.internet.headers.http;

/**
 * Protobuf type {@code xray.transport.internet.headers.http.ResponseConfig}
 */
public final class ResponseConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.transport.internet.headers.http.ResponseConfig)
    ResponseConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseConfig.newBuilder() to construct.
  private ResponseConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseConfig() {
    header_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.paolu.xray.transport.internet.headers.http.ConfigOuterClass.internal_static_xray_transport_internet_headers_http_ResponseConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.paolu.xray.transport.internet.headers.http.ConfigOuterClass.internal_static_xray_transport_internet_headers_http_ResponseConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.class, cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private cloud.paolu.xray.transport.internet.headers.http.Version version_;
  /**
   * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.Version getVersion() {
    return version_ == null ? cloud.paolu.xray.transport.internet.headers.http.Version.getDefaultInstance() : version_;
  }
  /**
   * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.VersionOrBuilder getVersionOrBuilder() {
    return version_ == null ? cloud.paolu.xray.transport.internet.headers.http.Version.getDefaultInstance() : version_;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private cloud.paolu.xray.transport.internet.headers.http.Status status_;
  /**
   * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.Status getStatus() {
    return status_ == null ? cloud.paolu.xray.transport.internet.headers.http.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? cloud.paolu.xray.transport.internet.headers.http.Status.getDefaultInstance() : status_;
  }

  public static final int HEADER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.transport.internet.headers.http.Header> header_;
  /**
   * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.transport.internet.headers.http.Header> getHeaderList() {
    return header_;
  }
  /**
   * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder> 
      getHeaderOrBuilderList() {
    return header_;
  }
  /**
   * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
   */
  @java.lang.Override
  public int getHeaderCount() {
    return header_.size();
  }
  /**
   * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.Header getHeader(int index) {
    return header_.get(index);
  }
  /**
   * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder getHeaderOrBuilder(
      int index) {
    return header_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != null) {
      output.writeMessage(1, getVersion());
    }
    if (status_ != null) {
      output.writeMessage(2, getStatus());
    }
    for (int i = 0; i < header_.size(); i++) {
      output.writeMessage(3, header_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    for (int i = 0; i < header_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, header_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.paolu.xray.transport.internet.headers.http.ResponseConfig)) {
      return super.equals(obj);
    }
    cloud.paolu.xray.transport.internet.headers.http.ResponseConfig other = (cloud.paolu.xray.transport.internet.headers.http.ResponseConfig) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getHeaderList()
        .equals(other.getHeaderList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (getHeaderCount() > 0) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.paolu.xray.transport.internet.headers.http.ResponseConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.transport.internet.headers.http.ResponseConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.transport.internet.headers.http.ResponseConfig)
      cloud.paolu.xray.transport.internet.headers.http.ResponseConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.paolu.xray.transport.internet.headers.http.ConfigOuterClass.internal_static_xray_transport_internet_headers_http_ResponseConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.paolu.xray.transport.internet.headers.http.ConfigOuterClass.internal_static_xray_transport_internet_headers_http_ResponseConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.class, cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.Builder.class);
    }

    // Construct using cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = null;
      if (versionBuilder_ != null) {
        versionBuilder_.dispose();
        versionBuilder_ = null;
      }
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
      } else {
        header_ = null;
        headerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.paolu.xray.transport.internet.headers.http.ConfigOuterClass.internal_static_xray_transport_internet_headers_http_ResponseConfig_descriptor;
    }

    @java.lang.Override
    public cloud.paolu.xray.transport.internet.headers.http.ResponseConfig getDefaultInstanceForType() {
      return cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.paolu.xray.transport.internet.headers.http.ResponseConfig build() {
      cloud.paolu.xray.transport.internet.headers.http.ResponseConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.paolu.xray.transport.internet.headers.http.ResponseConfig buildPartial() {
      cloud.paolu.xray.transport.internet.headers.http.ResponseConfig result = new cloud.paolu.xray.transport.internet.headers.http.ResponseConfig(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.paolu.xray.transport.internet.headers.http.ResponseConfig result) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          header_ = java.util.Collections.unmodifiableList(header_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
    }

    private void buildPartial0(cloud.paolu.xray.transport.internet.headers.http.ResponseConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = versionBuilder_ == null
            ? version_
            : versionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.paolu.xray.transport.internet.headers.http.ResponseConfig) {
        return mergeFrom((cloud.paolu.xray.transport.internet.headers.http.ResponseConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.paolu.xray.transport.internet.headers.http.ResponseConfig other) {
      if (other == cloud.paolu.xray.transport.internet.headers.http.ResponseConfig.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (headerBuilder_ == null) {
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
      } else {
        if (!other.header_.isEmpty()) {
          if (headerBuilder_.isEmpty()) {
            headerBuilder_.dispose();
            headerBuilder_ = null;
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000004);
            headerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeaderFieldBuilder() : null;
          } else {
            headerBuilder_.addAllMessages(other.header_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getVersionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              cloud.paolu.xray.transport.internet.headers.http.Header m =
                  input.readMessage(
                      cloud.paolu.xray.transport.internet.headers.http.Header.parser(),
                      extensionRegistry);
              if (headerBuilder_ == null) {
                ensureHeaderIsMutable();
                header_.add(m);
              } else {
                headerBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private cloud.paolu.xray.transport.internet.headers.http.Version version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Version, cloud.paolu.xray.transport.internet.headers.http.Version.Builder, cloud.paolu.xray.transport.internet.headers.http.VersionOrBuilder> versionBuilder_;
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     * @return The version.
     */
    public cloud.paolu.xray.transport.internet.headers.http.Version getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? cloud.paolu.xray.transport.internet.headers.http.Version.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder setVersion(cloud.paolu.xray.transport.internet.headers.http.Version value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
      } else {
        versionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder setVersion(
        cloud.paolu.xray.transport.internet.headers.http.Version.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder mergeVersion(cloud.paolu.xray.transport.internet.headers.http.Version value) {
      if (versionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          version_ != null &&
          version_ != cloud.paolu.xray.transport.internet.headers.http.Version.getDefaultInstance()) {
          getVersionBuilder().mergeFrom(value);
        } else {
          version_ = value;
        }
      } else {
        versionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = null;
      if (versionBuilder_ != null) {
        versionBuilder_.dispose();
        versionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Version.Builder getVersionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.VersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            cloud.paolu.xray.transport.internet.headers.http.Version.getDefaultInstance() : version_;
      }
    }
    /**
     * <code>.xray.transport.internet.headers.http.Version version = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Version, cloud.paolu.xray.transport.internet.headers.http.Version.Builder, cloud.paolu.xray.transport.internet.headers.http.VersionOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cloud.paolu.xray.transport.internet.headers.http.Version, cloud.paolu.xray.transport.internet.headers.http.Version.Builder, cloud.paolu.xray.transport.internet.headers.http.VersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private cloud.paolu.xray.transport.internet.headers.http.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Status, cloud.paolu.xray.transport.internet.headers.http.Status.Builder, cloud.paolu.xray.transport.internet.headers.http.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     * @return The status.
     */
    public cloud.paolu.xray.transport.internet.headers.http.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? cloud.paolu.xray.transport.internet.headers.http.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public Builder setStatus(cloud.paolu.xray.transport.internet.headers.http.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public Builder setStatus(
        cloud.paolu.xray.transport.internet.headers.http.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public Builder mergeStatus(cloud.paolu.xray.transport.internet.headers.http.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          status_ != null &&
          status_ != cloud.paolu.xray.transport.internet.headers.http.Status.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            cloud.paolu.xray.transport.internet.headers.http.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.xray.transport.internet.headers.http.Status status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Status, cloud.paolu.xray.transport.internet.headers.http.Status.Builder, cloud.paolu.xray.transport.internet.headers.http.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cloud.paolu.xray.transport.internet.headers.http.Status, cloud.paolu.xray.transport.internet.headers.http.Status.Builder, cloud.paolu.xray.transport.internet.headers.http.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private java.util.List<cloud.paolu.xray.transport.internet.headers.http.Header> header_ =
      java.util.Collections.emptyList();
    private void ensureHeaderIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        header_ = new java.util.ArrayList<cloud.paolu.xray.transport.internet.headers.http.Header>(header_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Header, cloud.paolu.xray.transport.internet.headers.http.Header.Builder, cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder> headerBuilder_;

    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public java.util.List<cloud.paolu.xray.transport.internet.headers.http.Header> getHeaderList() {
      if (headerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(header_);
      } else {
        return headerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public int getHeaderCount() {
      if (headerBuilder_ == null) {
        return header_.size();
      } else {
        return headerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Header getHeader(int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);
      } else {
        return headerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder setHeader(
        int index, cloud.paolu.xray.transport.internet.headers.http.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
      } else {
        headerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder setHeader(
        int index, cloud.paolu.xray.transport.internet.headers.http.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.set(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder addHeader(cloud.paolu.xray.transport.internet.headers.http.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
      } else {
        headerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder addHeader(
        int index, cloud.paolu.xray.transport.internet.headers.http.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(index, value);
        onChanged();
      } else {
        headerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder addHeader(
        cloud.paolu.xray.transport.internet.headers.http.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder addHeader(
        int index, cloud.paolu.xray.transport.internet.headers.http.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder addAllHeader(
        java.lang.Iterable<? extends cloud.paolu.xray.transport.internet.headers.http.Header> values) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, header_);
        onChanged();
      } else {
        headerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        headerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public Builder removeHeader(int index) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.remove(index);
        onChanged();
      } else {
        headerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Header.Builder getHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);  } else {
        return headerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder> 
         getHeaderOrBuilderList() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(header_);
      }
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Header.Builder addHeaderBuilder() {
      return getHeaderFieldBuilder().addBuilder(
          cloud.paolu.xray.transport.internet.headers.http.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public cloud.paolu.xray.transport.internet.headers.http.Header.Builder addHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().addBuilder(
          index, cloud.paolu.xray.transport.internet.headers.http.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.transport.internet.headers.http.Header header = 3;</code>
     */
    public java.util.List<cloud.paolu.xray.transport.internet.headers.http.Header.Builder> 
         getHeaderBuilderList() {
      return getHeaderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.transport.internet.headers.http.Header, cloud.paolu.xray.transport.internet.headers.http.Header.Builder, cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.transport.internet.headers.http.Header, cloud.paolu.xray.transport.internet.headers.http.Header.Builder, cloud.paolu.xray.transport.internet.headers.http.HeaderOrBuilder>(
                header_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.transport.internet.headers.http.ResponseConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.transport.internet.headers.http.ResponseConfig)
  private static final cloud.paolu.xray.transport.internet.headers.http.ResponseConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.paolu.xray.transport.internet.headers.http.ResponseConfig();
  }

  public static cloud.paolu.xray.transport.internet.headers.http.ResponseConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseConfig>
      PARSER = new com.google.protobuf.AbstractParser<ResponseConfig>() {
    @java.lang.Override
    public ResponseConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResponseConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.paolu.xray.transport.internet.headers.http.ResponseConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

