// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/blackhole/config.proto

package cloud.paolu.xray.proxy.blackhole;

public interface NoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.blackhole.NoneResponse)
    com.google.protobuf.MessageOrBuilder {
}
