// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/http/config.proto

package cloud.paolu.xray.proxy.http;

public interface ClientConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.http.ClientConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Sever is a list of HTTP server addresses.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  java.util.List<cloud.paolu.xray.common.protocol.ServerEndpoint> 
      getServerList();
  /**
   * <pre>
   * Sever is a list of HTTP server addresses.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  cloud.paolu.xray.common.protocol.ServerEndpoint getServer(int index);
  /**
   * <pre>
   * Sever is a list of HTTP server addresses.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  int getServerCount();
  /**
   * <pre>
   * Sever is a list of HTTP server addresses.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  java.util.List<? extends cloud.paolu.xray.common.protocol.ServerEndpointOrBuilder> 
      getServerOrBuilderList();
  /**
   * <pre>
   * Sever is a list of HTTP server addresses.
   * </pre>
   *
   * <code>repeated .xray.common.protocol.ServerEndpoint server = 1;</code>
   */
  cloud.paolu.xray.common.protocol.ServerEndpointOrBuilder getServerOrBuilder(
      int index);

  /**
   * <code>repeated .xray.proxy.http.Header header = 2;</code>
   */
  java.util.List<cloud.paolu.xray.proxy.http.Header> 
      getHeaderList();
  /**
   * <code>repeated .xray.proxy.http.Header header = 2;</code>
   */
  cloud.paolu.xray.proxy.http.Header getHeader(int index);
  /**
   * <code>repeated .xray.proxy.http.Header header = 2;</code>
   */
  int getHeaderCount();
  /**
   * <code>repeated .xray.proxy.http.Header header = 2;</code>
   */
  java.util.List<? extends cloud.paolu.xray.proxy.http.HeaderOrBuilder> 
      getHeaderOrBuilderList();
  /**
   * <code>repeated .xray.proxy.http.Header header = 2;</code>
   */
  cloud.paolu.xray.proxy.http.HeaderOrBuilder getHeaderOrBuilder(
      int index);
}
