// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/log/log.proto

package cloud.paolu.xray.common.log;

public final class Log {
  private Log() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024common/log/log.proto\022\017xray.common.log*" +
      "D\n\010Severity\022\013\n\007Unknown\020\000\022\t\n\005Error\020\001\022\013\n\007W" +
      "arning\020\002\022\010\n\004Info\020\003\022\t\n\005Debug\020\004BW\n\033cloud.p" +
      "aolu.xray.common.logP\001Z$github.com/xtls/" +
      "xray-core/common/log\252\002\017Xray.Common.Logb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
