// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package cloud.paolu.xray.app.router.command;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RoutingContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RoutingContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_RoutingContext_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_TestRouteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_TestRouteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_router_command_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_router_command_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n app/router/command/command.proto\022\027xray" +
      ".app.router.command\032\030common/net/network." +
      "proto\"\203\003\n\016RoutingContext\022\022\n\nInboundTag\030\001" +
      " \001(\t\022)\n\007Network\030\002 \001(\0162\030.xray.common.net." +
      "Network\022\021\n\tSourceIPs\030\003 \003(\014\022\021\n\tTargetIPs\030" +
      "\004 \003(\014\022\022\n\nSourcePort\030\005 \001(\r\022\022\n\nTargetPort\030" +
      "\006 \001(\r\022\024\n\014TargetDomain\030\007 \001(\t\022\020\n\010Protocol\030" +
      "\010 \001(\t\022\014\n\004User\030\t \001(\t\022K\n\nAttributes\030\n \003(\0132" +
      "7.xray.app.router.command.RoutingContext" +
      ".AttributesEntry\022\031\n\021OutboundGroupTags\030\013 " +
      "\003(\t\022\023\n\013OutboundTag\030\014 \001(\t\0321\n\017AttributesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"6\n\034S" +
      "ubscribeRoutingStatsRequest\022\026\n\016FieldSele" +
      "ctors\030\001 \003(\t\"\202\001\n\020TestRouteRequest\022?\n\016Rout" +
      "ingContext\030\001 \001(\0132\'.xray.app.router.comma" +
      "nd.RoutingContext\022\026\n\016FieldSelectors\030\002 \003(" +
      "\t\022\025\n\rPublishResult\030\003 \001(\010\"\010\n\006Config2\360\001\n\016R" +
      "outingService\022{\n\025SubscribeRoutingStats\0225" +
      ".xray.app.router.command.SubscribeRoutin" +
      "gStatsRequest\032\'.xray.app.router.command." +
      "RoutingContext\"\0000\001\022a\n\tTestRoute\022).xray.a" +
      "pp.router.command.TestRouteRequest\032\'.xra" +
      "y.app.router.command.RoutingContext\"\000Bo\n" +
      "#cloud.paolu.xray.app.router.commandP\001Z," +
      "github.com/xtls/xray-core/app/router/com" +
      "mand\252\002\027Xray.App.Router.Commandb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.net.NetworkOuterClass.getDescriptor(),
        });
    internal_static_xray_app_router_command_RoutingContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_router_command_RoutingContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RoutingContext_descriptor,
        new java.lang.String[] { "InboundTag", "Network", "SourceIPs", "TargetIPs", "SourcePort", "TargetPort", "TargetDomain", "Protocol", "User", "Attributes", "OutboundGroupTags", "OutboundTag", });
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor =
      internal_static_xray_app_router_command_RoutingContext_descriptor.getNestedTypes().get(0);
    internal_static_xray_app_router_command_RoutingContext_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_RoutingContext_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_SubscribeRoutingStatsRequest_descriptor,
        new java.lang.String[] { "FieldSelectors", });
    internal_static_xray_app_router_command_TestRouteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xray_app_router_command_TestRouteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_TestRouteRequest_descriptor,
        new java.lang.String[] { "RoutingContext", "FieldSelectors", "PublishResult", });
    internal_static_xray_app_router_command_Config_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_xray_app_router_command_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_router_command_Config_descriptor,
        new java.lang.String[] { });
    cloud.paolu.xray.common.net.NetworkOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
