// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package cloud.paolu.xray.app.router.command;

public interface TestRouteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.command.TestRouteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   * @return Whether the routingContext field is set.
   */
  boolean hasRoutingContext();
  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   * @return The routingContext.
   */
  cloud.paolu.xray.app.router.command.RoutingContext getRoutingContext();
  /**
   * <code>.xray.app.router.command.RoutingContext RoutingContext = 1;</code>
   */
  cloud.paolu.xray.app.router.command.RoutingContextOrBuilder getRoutingContextOrBuilder();

  /**
   * <code>repeated string FieldSelectors = 2;</code>
   * @return A list containing the fieldSelectors.
   */
  java.util.List<java.lang.String>
      getFieldSelectorsList();
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   * @return The count of fieldSelectors.
   */
  int getFieldSelectorsCount();
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   * @param index The index of the element to return.
   * @return The fieldSelectors at the given index.
   */
  java.lang.String getFieldSelectors(int index);
  /**
   * <code>repeated string FieldSelectors = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldSelectors at the given index.
   */
  com.google.protobuf.ByteString
      getFieldSelectorsBytes(int index);

  /**
   * <code>bool PublishResult = 3;</code>
   * @return The publishResult.
   */
  boolean getPublishResult();
}
