// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/headers/dns/config.proto

package cloud.paolu.xray.transport.internet.headers.dns;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_headers_dns_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_headers_dns_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+transport/internet/headers/dns/config." +
      "proto\022#xray.transport.internet.headers.d" +
      "ns\"\030\n\006Config\022\016\n\006domain\030\001 \001(\tB\223\001\n/cloud.p" +
      "aolu.xray.transport.internet.headers.dns" +
      "P\001Z8github.com/xtls/xray-core/transport/" +
      "internet/headers/dns\252\002#Xray.Transport.In" +
      "ternet.Headers.DNSb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xray_transport_internet_headers_dns_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_headers_dns_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_headers_dns_Config_descriptor,
        new java.lang.String[] { "Domain", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
