// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/headers/noop/config.proto

package cloud.paolu.xray.transport.internet.headers.noop;

public interface ConnectionConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.headers.noop.ConnectionConfig)
    com.google.protobuf.MessageOrBuilder {
}
