// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/command/command.proto

package cloud.paolu.xray.app.proxyman.command;

public interface AlterOutboundRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.command.AlterOutboundRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>.xray.common.serial.TypedMessage operation = 2;</code>
   * @return Whether the operation field is set.
   */
  boolean hasOperation();
  /**
   * <code>.xray.common.serial.TypedMessage operation = 2;</code>
   * @return The operation.
   */
  cloud.paolu.xray.common.serial.TypedMessage getOperation();
  /**
   * <code>.xray.common.serial.TypedMessage operation = 2;</code>
   */
  cloud.paolu.xray.common.serial.TypedMessageOrBuilder getOperationOrBuilder();
}
