// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/dns/fakedns/fakedns.proto

package cloud.paolu.xray.app.dns.fakedns;

public final class Fakedns {
  private Fakedns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_dns_fakedns_FakeDnsPool_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_dns_fakedns_FakeDnsPool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_dns_fakedns_FakeDnsPoolMulti_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_dns_fakedns_FakeDnsPoolMulti_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035app/dns/fakedns/fakedns.proto\022\024xray.ap" +
      "p.dns.fakedns\"/\n\013FakeDnsPool\022\017\n\007ip_pool\030" +
      "\001 \001(\t\022\017\n\007lruSize\030\002 \001(\003\"D\n\020FakeDnsPoolMul" +
      "ti\0220\n\005pools\030\001 \003(\0132!.xray.app.dns.fakedns" +
      ".FakeDnsPoolBf\n cloud.paolu.xray.app.dns" +
      ".fakednsP\001Z)github.com/xtls/xray-core/ap" +
      "p/dns/fakedns\252\002\024Xray.App.Dns.Fakednsb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xray_app_dns_fakedns_FakeDnsPool_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_dns_fakedns_FakeDnsPool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_dns_fakedns_FakeDnsPool_descriptor,
        new java.lang.String[] { "IpPool", "LruSize", });
    internal_static_xray_app_dns_fakedns_FakeDnsPoolMulti_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_dns_fakedns_FakeDnsPoolMulti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_dns_fakedns_FakeDnsPoolMulti_descriptor,
        new java.lang.String[] { "Pools", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
