// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/shadowsocks_2022/config.proto

package cloud.paolu.xray.proxy.shadowsocks_2022;

/**
 * Protobuf type {@code xray.proxy.shadowsocks_2022.MultiUserServerConfig}
 */
public final class MultiUserServerConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.proxy.shadowsocks_2022.MultiUserServerConfig)
    MultiUserServerConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiUserServerConfig.newBuilder() to construct.
  private MultiUserServerConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiUserServerConfig() {
    method_ = "";
    key_ = "";
    users_ = java.util.Collections.emptyList();
    network_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultiUserServerConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.paolu.xray.proxy.shadowsocks_2022.Config.internal_static_xray_proxy_shadowsocks_2022_MultiUserServerConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.paolu.xray.proxy.shadowsocks_2022.Config.internal_static_xray_proxy_shadowsocks_2022_MultiUserServerConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.class, cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.Builder.class);
  }

  public static final int METHOD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object method_ = "";
  /**
   * <code>string method = 1;</code>
   * @return The method.
   */
  @java.lang.Override
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 1;</code>
   * @return The bytes for method.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.proxy.shadowsocks_2022.User> users_;
  /**
   * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.proxy.shadowsocks_2022.User> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.proxy.shadowsocks_2022.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  public static final int NETWORK_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<java.lang.Integer> network_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, cloud.paolu.xray.common.net.Network> network_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, cloud.paolu.xray.common.net.Network>() {
            public cloud.paolu.xray.common.net.Network convert(java.lang.Integer from) {
              cloud.paolu.xray.common.net.Network result = cloud.paolu.xray.common.net.Network.forNumber(from);
              return result == null ? cloud.paolu.xray.common.net.Network.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .xray.common.net.Network network = 4;</code>
   * @return A list containing the network.
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.common.net.Network> getNetworkList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, cloud.paolu.xray.common.net.Network>(network_, network_converter_);
  }
  /**
   * <code>repeated .xray.common.net.Network network = 4;</code>
   * @return The count of network.
   */
  @java.lang.Override
  public int getNetworkCount() {
    return network_.size();
  }
  /**
   * <code>repeated .xray.common.net.Network network = 4;</code>
   * @param index The index of the element to return.
   * @return The network at the given index.
   */
  @java.lang.Override
  public cloud.paolu.xray.common.net.Network getNetwork(int index) {
    return network_converter_.convert(network_.get(index));
  }
  /**
   * <code>repeated .xray.common.net.Network network = 4;</code>
   * @return A list containing the enum numeric values on the wire for network.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getNetworkValueList() {
    return network_;
  }
  /**
   * <code>repeated .xray.common.net.Network network = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of network at the given index.
   */
  @java.lang.Override
  public int getNetworkValue(int index) {
    return network_.get(index);
  }
  private int networkMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, method_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(3, users_.get(i));
    }
    if (getNetworkList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(networkMemoizedSerializedSize);
    }
    for (int i = 0; i < network_.size(); i++) {
      output.writeEnumNoTag(network_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, method_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, users_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < network_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(network_.get(i));
      }
      size += dataSize;
      if (!getNetworkList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }networkMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig)) {
      return super.equals(obj);
    }
    cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig other = (cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig) obj;

    if (!getMethod()
        .equals(other.getMethod())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!network_.equals(other.network_)) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    if (getNetworkCount() > 0) {
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + network_.hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.proxy.shadowsocks_2022.MultiUserServerConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.proxy.shadowsocks_2022.MultiUserServerConfig)
      cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.paolu.xray.proxy.shadowsocks_2022.Config.internal_static_xray_proxy_shadowsocks_2022_MultiUserServerConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.paolu.xray.proxy.shadowsocks_2022.Config.internal_static_xray_proxy_shadowsocks_2022_MultiUserServerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.class, cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.Builder.class);
    }

    // Construct using cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      method_ = "";
      key_ = "";
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
      } else {
        users_ = null;
        usersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      network_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.paolu.xray.proxy.shadowsocks_2022.Config.internal_static_xray_proxy_shadowsocks_2022_MultiUserServerConfig_descriptor;
    }

    @java.lang.Override
    public cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig getDefaultInstanceForType() {
      return cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig build() {
      cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig buildPartial() {
      cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig result = new cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig result) {
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        network_ = java.util.Collections.unmodifiableList(network_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.network_ = network_;
    }

    private void buildPartial0(cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.method_ = method_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.key_ = key_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig) {
        return mergeFrom((cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig other) {
      if (other == cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig.getDefaultInstance()) return this;
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000004);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      if (!other.network_.isEmpty()) {
        if (network_.isEmpty()) {
          network_ = other.network_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureNetworkIsMutable();
          network_.addAll(other.network_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              method_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              cloud.paolu.xray.proxy.shadowsocks_2022.User m =
                  input.readMessage(
                      cloud.paolu.xray.proxy.shadowsocks_2022.User.parser(),
                      extensionRegistry);
              if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(m);
              } else {
                usersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              int tmpRaw = input.readEnum();
              ensureNetworkIsMutable();
              network_.add(tmpRaw);
              break;
            } // case 32
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureNetworkIsMutable();
                network_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 1;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 1;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 1;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      method_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      method_ = getDefaultInstance().getMethod();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string method = 1;</code>
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      method_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<cloud.paolu.xray.proxy.shadowsocks_2022.User> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        users_ = new java.util.ArrayList<cloud.paolu.xray.proxy.shadowsocks_2022.User>(users_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.proxy.shadowsocks_2022.User, cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder, cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder> usersBuilder_;

    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public java.util.List<cloud.paolu.xray.proxy.shadowsocks_2022.User> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public cloud.paolu.xray.proxy.shadowsocks_2022.User getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder setUsers(
        int index, cloud.paolu.xray.proxy.shadowsocks_2022.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder setUsers(
        int index, cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder addUsers(cloud.paolu.xray.proxy.shadowsocks_2022.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder addUsers(
        int index, cloud.paolu.xray.proxy.shadowsocks_2022.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder addUsers(
        cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder addUsers(
        int index, cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends cloud.paolu.xray.proxy.shadowsocks_2022.User> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder getUsersBuilder(
        int index) {
      return getUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder addUsersBuilder() {
      return getUsersFieldBuilder().addBuilder(
          cloud.paolu.xray.proxy.shadowsocks_2022.User.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder addUsersBuilder(
        int index) {
      return getUsersFieldBuilder().addBuilder(
          index, cloud.paolu.xray.proxy.shadowsocks_2022.User.getDefaultInstance());
    }
    /**
     * <code>repeated .xray.proxy.shadowsocks_2022.User users = 3;</code>
     */
    public java.util.List<cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder> 
         getUsersBuilderList() {
      return getUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.proxy.shadowsocks_2022.User, cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder, cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.proxy.shadowsocks_2022.User, cloud.paolu.xray.proxy.shadowsocks_2022.User.Builder, cloud.paolu.xray.proxy.shadowsocks_2022.UserOrBuilder>(
                users_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }

    private java.util.List<java.lang.Integer> network_ =
      java.util.Collections.emptyList();
    private void ensureNetworkIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        network_ = new java.util.ArrayList<java.lang.Integer>(network_);
        bitField0_ |= 0x00000008;
      }
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @return A list containing the network.
     */
    public java.util.List<cloud.paolu.xray.common.net.Network> getNetworkList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, cloud.paolu.xray.common.net.Network>(network_, network_converter_);
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @return The count of network.
     */
    public int getNetworkCount() {
      return network_.size();
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param index The index of the element to return.
     * @return The network at the given index.
     */
    public cloud.paolu.xray.common.net.Network getNetwork(int index) {
      return network_converter_.convert(network_.get(index));
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param index The index to set the value at.
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        int index, cloud.paolu.xray.common.net.Network value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNetworkIsMutable();
      network_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param value The network to add.
     * @return This builder for chaining.
     */
    public Builder addNetwork(cloud.paolu.xray.common.net.Network value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNetworkIsMutable();
      network_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param values The network to add.
     * @return This builder for chaining.
     */
    public Builder addAllNetwork(
        java.lang.Iterable<? extends cloud.paolu.xray.common.net.Network> values) {
      ensureNetworkIsMutable();
      for (cloud.paolu.xray.common.net.Network value : values) {
        network_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      network_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @return A list containing the enum numeric values on the wire for network.
     */
    public java.util.List<java.lang.Integer>
    getNetworkValueList() {
      return java.util.Collections.unmodifiableList(network_);
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of network at the given index.
     */
    public int getNetworkValue(int index) {
      return network_.get(index);
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkValue(
        int index, int value) {
      ensureNetworkIsMutable();
      network_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param value The enum numeric value on the wire for network to add.
     * @return This builder for chaining.
     */
    public Builder addNetworkValue(int value) {
      ensureNetworkIsMutable();
      network_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .xray.common.net.Network network = 4;</code>
     * @param values The enum numeric values on the wire for network to add.
     * @return This builder for chaining.
     */
    public Builder addAllNetworkValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureNetworkIsMutable();
      for (int value : values) {
        network_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.proxy.shadowsocks_2022.MultiUserServerConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.proxy.shadowsocks_2022.MultiUserServerConfig)
  private static final cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig();
  }

  public static cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiUserServerConfig>
      PARSER = new com.google.protobuf.AbstractParser<MultiUserServerConfig>() {
    @java.lang.Override
    public MultiUserServerConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MultiUserServerConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultiUserServerConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.paolu.xray.proxy.shadowsocks_2022.MultiUserServerConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

