// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/shadowsocks_2022/config.proto

package cloud.paolu.xray.proxy.shadowsocks_2022;

public interface ServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.shadowsocks_2022.ServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string method = 1;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 1;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 level = 4;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>repeated .xray.common.net.Network network = 5;</code>
   * @return A list containing the network.
   */
  java.util.List<cloud.paolu.xray.common.net.Network> getNetworkList();
  /**
   * <code>repeated .xray.common.net.Network network = 5;</code>
   * @return The count of network.
   */
  int getNetworkCount();
  /**
   * <code>repeated .xray.common.net.Network network = 5;</code>
   * @param index The index of the element to return.
   * @return The network at the given index.
   */
  cloud.paolu.xray.common.net.Network getNetwork(int index);
  /**
   * <code>repeated .xray.common.net.Network network = 5;</code>
   * @return A list containing the enum numeric values on the wire for network.
   */
  java.util.List<java.lang.Integer>
  getNetworkValueList();
  /**
   * <code>repeated .xray.common.net.Network network = 5;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of network at the given index.
   */
  int getNetworkValue(int index);
}
