spring:
  # Redis配置 （SSO模式一和模式二使用Redis来同步会话）
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:zw6e6ELHoG}
    url: jdbc:mysql://${MYSQL_HOST:10.10.10.11}:${MYSQL_PORT:30868}/${MYSQL_DATABASE:xpanel}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    hikari:
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      #最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒。
      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      #连接测试查询
      connection-test-query: SELECT 1
casdoor:
  endpoint: ${CASDOOR_ENDPOINT:http://10.10.10.12:54741}
  callback: ${CASDOOR_CALLBACK:http://10.10.10.15:8080}
  client-id: ${CASDOOR_CLIENT_ID:0988d1421b7b24b34b0e}
  client-secret: ${CASDOOR_CLIENT_SECERT:486b4c7f74e4bf6594757f081795b5b853892d40}
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE3zCCAsegAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCkxETAPBgNVBAoTCGh4
    ZGNsb3VkMRQwEgYDVQQDDAtjZXJ0X3hmdng2ajAeFw0yMzA3MTgwMjQ0NThaFw00
    MzA3MTgwMjQ0NThaMCkxETAPBgNVBAoTCGh4ZGNsb3VkMRQwEgYDVQQDDAtjZXJ0
    X3hmdng2ajCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMypyv4E4FHF
    +zdbeTWwmTqF22k+XKRnBShCNSh71iFI//AkiE6Ux6P1l3Ij6npgetMuu/Qa0liW
    U0x0OzPMJUJ2jEfFbS59Lmdpdskc56yVDuQjhxPStgwzwqr6qr+p0y5j6BB/Qwo3
    2OYOn0TD+HH4s+E7DDZyJlnWTrY4xk+3ahMNwpGgVUKaVjlvb+BDSavdMm2WRrOt
    vZwFBdFUSHgtABYk6EDLaz/ytnJjWiL/BVH/BPBb489wYsKcf9W67+lzjsEzz6x2
    NbOPiig0BjZbFNN5QiNZU1TShYliH+LSBIwTFO0rYqnvsiQNQ/Di9UAkWl4cN8aJ
    juv50CJXeuwUcRIR+BC7UwmOKnv8AUqsWqlwGI9Q+yeiqeSpW5aLszchmV0MZH91
    2Cmj+IMXcFLCRTJxOzgBtiwJZEgWqFPYAx8Ud7b3tcE/Os9RHZaF/zxzZKwD7uG9
    cyEUJ0Xsphx8cBXMMCQ91vF/RF5cwg8Am0uxpE8r8rKLPW2hmOfrBRWFInKb9ClO
    edI+touCM0iG9GD5N3sILpOwnYpTo8oZo2jf6szuDjOTTbdR4uqdo1Kky4+diJER
    fIHYtRihv68ozFd7MYGrEv4W2TX20NDoLzkuJbNd92juQGF46LyZUPlEQPdTtN5Y
    jUm/aZfc4wd7DDkuc+RKrY+CBUkbEqLfAgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAw
    DQYJKoZIhvcNAQELBQADggIBAFulp4EeIi5zWgXakoQZk7Qx+mHsLGrUCobXxJJ+
    XbQAL6RLIGgi49MHLdch7k0GZA0T0+fev+5nvNVV7cG2BHEfDoBGfJ1iHUSXCLN3
    S9mfJ6EJfPa0PpvSX7q94cRL+33KX7WdN3rg4TaxcVh0zu4mppcohGO33oe6d7Ax
    ZeEmLU36nhbQx/tCY7gklPloRzQ6ziIJdsSWdI46+48SpiEdIj9RRcHd6KG4ymwB
    +Nc8SCvdzB71hqle6a+lqMzwh8SZ0+CUa5BdFtEI1UsJP9x71h6wGblMNsL/kSMZ
    BbzCgUxMX5jcgARGu8BEhGMGGVqzZjv1AmFDqsIk1NSRdjaNAa55b1buy4mP3MuD
    IpB849jAXxf+FRKsEUzw3PxTEFfjou6OHhmZrmWaS07qwQugYEPk68VqNDzOfrx1
    KsOpVGCG4nK1bnhKCR8AH1Z7f6Vvo2GLGmPt7zcnsG3xvGtRvwT8Ne8BcHO9Wyrq
    +QjKBRDHek5bqa0Y5cNbrfvyK4YiPU9KOhCFuhZbSInashQdSmii1cazFRF5rEy9
    qi6Ocex1jXbftBshKBA7QswYW03N1mWeAeaWBYzqqGn+md9kf1Oj/H+uV68zDiHz
    xM3RQpbog4kYLWkBEvf7s6GZyKWn+oGGN8/WgI4wOYMuv7kx4lIl5+JbJNeYEND/
    WlNC
    -----END CERTIFICATE-----
  organization-name: hxdcloud
  application-name: x-panel
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml