spring:
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:redis-master}
      port: 6379
      password: ${REDIS_PASSWORD:LXjBLU8ZbD}
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:zw6e6ELHoG}
    url: jdbc:mysql://${MYSQL_HOST:10.10.10.11}:${MYSQL_PORT:30868}/${MYSQL_DATABASE:xpanel}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    hikari:
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      #最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒。
      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      #连接测试查询
      connection-test-query: SELECT 1
casdoor:
  endpoint: ${CASDOOR_ENDPOINT:http://10.10.10.12:54741}
  callback: ${CASDOOR_CALLBACK:http://10.10.10.15:8080}
  client-id: ${CASDOOR_CLIENT_ID:0988d1421b7b24b34b0e}
  client-secret: ${CASDOOR_CLIENT_SECERT:486b4c7f74e4bf6594757f081795b5b853892d40}
  certificate: ${CASDOOR_CERTIFICATE}
  organization-name: ${CASDOOR_ORGANIZATION_NAME}
  application-name: ${CASDOOR_APPLICATION_NAME}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
nnr:
  name: wangxingrui1997@gmail.com
  passwd: f878b0516d60267235c475815681726c
  token: 2e7bb01a-4a11-4f09-b441-52a1d363a515
retrofit:
  # 全局重试配置
  global-retry:
    # 是否启用全局重试
    enable: true
    # 全局重试间隔时间
    interval-ms: 100
    # 全局最大重试次数
    max-retries: 2
    # 全局重试规则
    retry-rules:
      - OCCUR_EXCEPTION