// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vless/outbound/config.proto

package cloud.paolu.xray.proxy.vless.outbound;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_proxy_vless_outbound_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_proxy_vless_outbound_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proxy/vless/outbound/config.proto\022\031xra" +
      "y.proxy.vless.outbound\032!common/protocol/" +
      "server_spec.proto\"=\n\006Config\0223\n\005vnext\030\001 \003" +
      "(\0132$.xray.common.protocol.ServerEndpoint" +
      "Bu\n%cloud.paolu.xray.proxy.vless.outboun" +
      "dP\001Z.github.com/xtls/xray-core/proxy/vle" +
      "ss/outbound\252\002\031Xray.Proxy.Vless.Outboundb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.protocol.ServerSpec.getDescriptor(),
        });
    internal_static_xray_proxy_vless_outbound_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_proxy_vless_outbound_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_proxy_vless_outbound_Config_descriptor,
        new java.lang.String[] { "Vnext", });
    cloud.paolu.xray.common.protocol.ServerSpec.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
