// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/protocol/user.proto

package cloud.paolu.xray.common.protocol;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_common_protocol_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_common_protocol_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032common/protocol/user.proto\022\024xray.commo" +
      "n.protocol\032!common/serial/typed_message." +
      "proto\"W\n\004User\022\r\n\005level\030\001 \001(\r\022\r\n\005email\030\002 " +
      "\001(\t\0221\n\007account\030\003 \001(\0132 .xray.common.seria" +
      "l.TypedMessageBf\n cloud.paolu.xray.commo" +
      "n.protocolP\001Z)github.com/xtls/xray-core/" +
      "common/protocol\252\002\024Xray.Common.Protocolb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
        });
    internal_static_xray_common_protocol_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_common_protocol_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_common_protocol_User_descriptor,
        new java.lang.String[] { "Level", "Email", "Account", });
    cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
