// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/protocol/user.proto

package cloud.paolu.xray.common.protocol;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.common.protocol.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * Protocol specific account information. Must be the account proto in one of
   * the proxies.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage account = 3;</code>
   * @return Whether the account field is set.
   */
  boolean hasAccount();
  /**
   * <pre>
   * Protocol specific account information. Must be the account proto in one of
   * the proxies.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage account = 3;</code>
   * @return The account.
   */
  cloud.paolu.xray.common.serial.TypedMessage getAccount();
  /**
   * <pre>
   * Protocol specific account information. Must be the account proto in one of
   * the proxies.
   * </pre>
   *
   * <code>.xray.common.serial.TypedMessage account = 3;</code>
   */
  cloud.paolu.xray.common.serial.TypedMessageOrBuilder getAccountOrBuilder();
}
