// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/commander/config.proto

package cloud.paolu.xray.app.commander;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_commander_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_commander_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_commander_ReflectionConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_commander_ReflectionConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032app/commander/config.proto\022\022xray.app.c" +
      "ommander\032!common/serial/typed_message.pr" +
      "oto\"H\n\006Config\022\013\n\003tag\030\001 \001(\t\0221\n\007service\030\002 " +
      "\003(\0132 .xray.common.serial.TypedMessage\"\022\n" +
      "\020ReflectionConfigB`\n\036cloud.paolu.xray.ap" +
      "p.commanderP\001Z\'github.com/xtls/xray-core" +
      "/app/commander\252\002\022Xray.App.Commanderb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
        });
    internal_static_xray_app_commander_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_commander_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_commander_Config_descriptor,
        new java.lang.String[] { "Tag", "Service", });
    internal_static_xray_app_commander_ReflectionConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_commander_ReflectionConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_commander_ReflectionConfig_descriptor,
        new java.lang.String[] { });
    cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
