// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/config.proto

package cloud.paolu.xray.core;

/**
 * <pre>
 * Config is the master config of Xray. Xray takes this config as input and
 * functions accordingly.
 * </pre>
 *
 * Protobuf type {@code xray.core.Config}
 */
public final class Config extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.core.Config)
    ConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Config() {
    inbound_ = java.util.Collections.emptyList();
    outbound_ = java.util.Collections.emptyList();
    app_ = java.util.Collections.emptyList();
    extension_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Config();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.paolu.xray.core.ConfigOuterClass.internal_static_xray_core_Config_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.paolu.xray.core.ConfigOuterClass.internal_static_xray_core_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.paolu.xray.core.Config.class, cloud.paolu.xray.core.Config.Builder.class);
  }

  public static final int INBOUND_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.core.InboundHandlerConfig> inbound_;
  /**
   * <pre>
   * Inbound handler configurations. Must have at least one item.
   * </pre>
   *
   * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.core.InboundHandlerConfig> getInboundList() {
    return inbound_;
  }
  /**
   * <pre>
   * Inbound handler configurations. Must have at least one item.
   * </pre>
   *
   * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.core.InboundHandlerConfigOrBuilder> 
      getInboundOrBuilderList() {
    return inbound_;
  }
  /**
   * <pre>
   * Inbound handler configurations. Must have at least one item.
   * </pre>
   *
   * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  @java.lang.Override
  public int getInboundCount() {
    return inbound_.size();
  }
  /**
   * <pre>
   * Inbound handler configurations. Must have at least one item.
   * </pre>
   *
   * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.core.InboundHandlerConfig getInbound(int index) {
    return inbound_.get(index);
  }
  /**
   * <pre>
   * Inbound handler configurations. Must have at least one item.
   * </pre>
   *
   * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.core.InboundHandlerConfigOrBuilder getInboundOrBuilder(
      int index) {
    return inbound_.get(index);
  }

  public static final int OUTBOUND_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.core.OutboundHandlerConfig> outbound_;
  /**
   * <pre>
   * Outbound handler configurations. Must have at least one item. The first
   * item is used as default for routing.
   * </pre>
   *
   * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.core.OutboundHandlerConfig> getOutboundList() {
    return outbound_;
  }
  /**
   * <pre>
   * Outbound handler configurations. Must have at least one item. The first
   * item is used as default for routing.
   * </pre>
   *
   * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder> 
      getOutboundOrBuilderList() {
    return outbound_;
  }
  /**
   * <pre>
   * Outbound handler configurations. Must have at least one item. The first
   * item is used as default for routing.
   * </pre>
   *
   * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
   */
  @java.lang.Override
  public int getOutboundCount() {
    return outbound_.size();
  }
  /**
   * <pre>
   * Outbound handler configurations. Must have at least one item. The first
   * item is used as default for routing.
   * </pre>
   *
   * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.core.OutboundHandlerConfig getOutbound(int index) {
    return outbound_.get(index);
  }
  /**
   * <pre>
   * Outbound handler configurations. Must have at least one item. The first
   * item is used as default for routing.
   * </pre>
   *
   * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder getOutboundOrBuilder(
      int index) {
    return outbound_.get(index);
  }

  public static final int APP_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.common.serial.TypedMessage> app_;
  /**
   * <pre>
   * App is for configurations of all features in Xray. A feature must
   * implement the Feature interface, and its config type must be registered
   * through common.RegisterConfig.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.common.serial.TypedMessage> getAppList() {
    return app_;
  }
  /**
   * <pre>
   * App is for configurations of all features in Xray. A feature must
   * implement the Feature interface, and its config type must be registered
   * through common.RegisterConfig.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
      getAppOrBuilderList() {
    return app_;
  }
  /**
   * <pre>
   * App is for configurations of all features in Xray. A feature must
   * implement the Feature interface, and its config type must be registered
   * through common.RegisterConfig.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
   */
  @java.lang.Override
  public int getAppCount() {
    return app_.size();
  }
  /**
   * <pre>
   * App is for configurations of all features in Xray. A feature must
   * implement the Feature interface, and its config type must be registered
   * through common.RegisterConfig.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.common.serial.TypedMessage getApp(int index) {
    return app_.get(index);
  }
  /**
   * <pre>
   * App is for configurations of all features in Xray. A feature must
   * implement the Feature interface, and its config type must be registered
   * through common.RegisterConfig.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.common.serial.TypedMessageOrBuilder getAppOrBuilder(
      int index) {
    return app_.get(index);
  }

  public static final int TRANSPORT_FIELD_NUMBER = 5;
  private cloud.paolu.xray.transport.global.Config transport_;
  /**
   * <pre>
   * Transport settings.
   * Deprecated. Each inbound and outbound should choose their own transport
   * config. Date to remove: 2020-01-13
   * </pre>
   *
   * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
   * @deprecated xray.core.Config.transport is deprecated.
   *     See core/config.proto;l=31
   * @return Whether the transport field is set.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean hasTransport() {
    return transport_ != null;
  }
  /**
   * <pre>
   * Transport settings.
   * Deprecated. Each inbound and outbound should choose their own transport
   * config. Date to remove: 2020-01-13
   * </pre>
   *
   * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
   * @deprecated xray.core.Config.transport is deprecated.
   *     See core/config.proto;l=31
   * @return The transport.
   */
  @java.lang.Override
  @java.lang.Deprecated public cloud.paolu.xray.transport.global.Config getTransport() {
    return transport_ == null ? cloud.paolu.xray.transport.global.Config.getDefaultInstance() : transport_;
  }
  /**
   * <pre>
   * Transport settings.
   * Deprecated. Each inbound and outbound should choose their own transport
   * config. Date to remove: 2020-01-13
   * </pre>
   *
   * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public cloud.paolu.xray.transport.global.ConfigOrBuilder getTransportOrBuilder() {
    return transport_ == null ? cloud.paolu.xray.transport.global.Config.getDefaultInstance() : transport_;
  }

  public static final int EXTENSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<cloud.paolu.xray.common.serial.TypedMessage> extension_;
  /**
   * <pre>
   * Configuration for extensions. The config may not work if corresponding
   * extension is not loaded into Xray. Xray will ignore such config during
   * initialization.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.paolu.xray.common.serial.TypedMessage> getExtensionList() {
    return extension_;
  }
  /**
   * <pre>
   * Configuration for extensions. The config may not work if corresponding
   * extension is not loaded into Xray. Xray will ignore such config during
   * initialization.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
      getExtensionOrBuilderList() {
    return extension_;
  }
  /**
   * <pre>
   * Configuration for extensions. The config may not work if corresponding
   * extension is not loaded into Xray. Xray will ignore such config during
   * initialization.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
   */
  @java.lang.Override
  public int getExtensionCount() {
    return extension_.size();
  }
  /**
   * <pre>
   * Configuration for extensions. The config may not work if corresponding
   * extension is not loaded into Xray. Xray will ignore such config during
   * initialization.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.common.serial.TypedMessage getExtension(int index) {
    return extension_.get(index);
  }
  /**
   * <pre>
   * Configuration for extensions. The config may not work if corresponding
   * extension is not loaded into Xray. Xray will ignore such config during
   * initialization.
   * </pre>
   *
   * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
   */
  @java.lang.Override
  public cloud.paolu.xray.common.serial.TypedMessageOrBuilder getExtensionOrBuilder(
      int index) {
    return extension_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < inbound_.size(); i++) {
      output.writeMessage(1, inbound_.get(i));
    }
    for (int i = 0; i < outbound_.size(); i++) {
      output.writeMessage(2, outbound_.get(i));
    }
    for (int i = 0; i < app_.size(); i++) {
      output.writeMessage(4, app_.get(i));
    }
    if (transport_ != null) {
      output.writeMessage(5, getTransport());
    }
    for (int i = 0; i < extension_.size(); i++) {
      output.writeMessage(6, extension_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < inbound_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, inbound_.get(i));
    }
    for (int i = 0; i < outbound_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, outbound_.get(i));
    }
    for (int i = 0; i < app_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, app_.get(i));
    }
    if (transport_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTransport());
    }
    for (int i = 0; i < extension_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, extension_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.paolu.xray.core.Config)) {
      return super.equals(obj);
    }
    cloud.paolu.xray.core.Config other = (cloud.paolu.xray.core.Config) obj;

    if (!getInboundList()
        .equals(other.getInboundList())) return false;
    if (!getOutboundList()
        .equals(other.getOutboundList())) return false;
    if (!getAppList()
        .equals(other.getAppList())) return false;
    if (hasTransport() != other.hasTransport()) return false;
    if (hasTransport()) {
      if (!getTransport()
          .equals(other.getTransport())) return false;
    }
    if (!getExtensionList()
        .equals(other.getExtensionList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInboundCount() > 0) {
      hash = (37 * hash) + INBOUND_FIELD_NUMBER;
      hash = (53 * hash) + getInboundList().hashCode();
    }
    if (getOutboundCount() > 0) {
      hash = (37 * hash) + OUTBOUND_FIELD_NUMBER;
      hash = (53 * hash) + getOutboundList().hashCode();
    }
    if (getAppCount() > 0) {
      hash = (37 * hash) + APP_FIELD_NUMBER;
      hash = (53 * hash) + getAppList().hashCode();
    }
    if (hasTransport()) {
      hash = (37 * hash) + TRANSPORT_FIELD_NUMBER;
      hash = (53 * hash) + getTransport().hashCode();
    }
    if (getExtensionCount() > 0) {
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.paolu.xray.core.Config parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.core.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.core.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.paolu.xray.core.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.paolu.xray.core.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.core.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.paolu.xray.core.Config prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Config is the master config of Xray. Xray takes this config as input and
   * functions accordingly.
   * </pre>
   *
   * Protobuf type {@code xray.core.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.core.Config)
      cloud.paolu.xray.core.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.paolu.xray.core.ConfigOuterClass.internal_static_xray_core_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.paolu.xray.core.ConfigOuterClass.internal_static_xray_core_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.paolu.xray.core.Config.class, cloud.paolu.xray.core.Config.Builder.class);
    }

    // Construct using cloud.paolu.xray.core.Config.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (inboundBuilder_ == null) {
        inbound_ = java.util.Collections.emptyList();
      } else {
        inbound_ = null;
        inboundBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (outboundBuilder_ == null) {
        outbound_ = java.util.Collections.emptyList();
      } else {
        outbound_ = null;
        outboundBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (appBuilder_ == null) {
        app_ = java.util.Collections.emptyList();
      } else {
        app_ = null;
        appBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      transport_ = null;
      if (transportBuilder_ != null) {
        transportBuilder_.dispose();
        transportBuilder_ = null;
      }
      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
      } else {
        extension_ = null;
        extensionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.paolu.xray.core.ConfigOuterClass.internal_static_xray_core_Config_descriptor;
    }

    @java.lang.Override
    public cloud.paolu.xray.core.Config getDefaultInstanceForType() {
      return cloud.paolu.xray.core.Config.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.paolu.xray.core.Config build() {
      cloud.paolu.xray.core.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.paolu.xray.core.Config buildPartial() {
      cloud.paolu.xray.core.Config result = new cloud.paolu.xray.core.Config(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.paolu.xray.core.Config result) {
      if (inboundBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          inbound_ = java.util.Collections.unmodifiableList(inbound_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.inbound_ = inbound_;
      } else {
        result.inbound_ = inboundBuilder_.build();
      }
      if (outboundBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          outbound_ = java.util.Collections.unmodifiableList(outbound_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.outbound_ = outbound_;
      } else {
        result.outbound_ = outboundBuilder_.build();
      }
      if (appBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          app_ = java.util.Collections.unmodifiableList(app_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.app_ = app_;
      } else {
        result.app_ = appBuilder_.build();
      }
      if (extensionBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          extension_ = java.util.Collections.unmodifiableList(extension_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.extension_ = extension_;
      } else {
        result.extension_ = extensionBuilder_.build();
      }
    }

    private void buildPartial0(cloud.paolu.xray.core.Config result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.transport_ = transportBuilder_ == null
            ? transport_
            : transportBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.paolu.xray.core.Config) {
        return mergeFrom((cloud.paolu.xray.core.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.paolu.xray.core.Config other) {
      if (other == cloud.paolu.xray.core.Config.getDefaultInstance()) return this;
      if (inboundBuilder_ == null) {
        if (!other.inbound_.isEmpty()) {
          if (inbound_.isEmpty()) {
            inbound_ = other.inbound_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInboundIsMutable();
            inbound_.addAll(other.inbound_);
          }
          onChanged();
        }
      } else {
        if (!other.inbound_.isEmpty()) {
          if (inboundBuilder_.isEmpty()) {
            inboundBuilder_.dispose();
            inboundBuilder_ = null;
            inbound_ = other.inbound_;
            bitField0_ = (bitField0_ & ~0x00000001);
            inboundBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInboundFieldBuilder() : null;
          } else {
            inboundBuilder_.addAllMessages(other.inbound_);
          }
        }
      }
      if (outboundBuilder_ == null) {
        if (!other.outbound_.isEmpty()) {
          if (outbound_.isEmpty()) {
            outbound_ = other.outbound_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOutboundIsMutable();
            outbound_.addAll(other.outbound_);
          }
          onChanged();
        }
      } else {
        if (!other.outbound_.isEmpty()) {
          if (outboundBuilder_.isEmpty()) {
            outboundBuilder_.dispose();
            outboundBuilder_ = null;
            outbound_ = other.outbound_;
            bitField0_ = (bitField0_ & ~0x00000002);
            outboundBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOutboundFieldBuilder() : null;
          } else {
            outboundBuilder_.addAllMessages(other.outbound_);
          }
        }
      }
      if (appBuilder_ == null) {
        if (!other.app_.isEmpty()) {
          if (app_.isEmpty()) {
            app_ = other.app_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAppIsMutable();
            app_.addAll(other.app_);
          }
          onChanged();
        }
      } else {
        if (!other.app_.isEmpty()) {
          if (appBuilder_.isEmpty()) {
            appBuilder_.dispose();
            appBuilder_ = null;
            app_ = other.app_;
            bitField0_ = (bitField0_ & ~0x00000004);
            appBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAppFieldBuilder() : null;
          } else {
            appBuilder_.addAllMessages(other.app_);
          }
        }
      }
      if (other.hasTransport()) {
        mergeTransport(other.getTransport());
      }
      if (extensionBuilder_ == null) {
        if (!other.extension_.isEmpty()) {
          if (extension_.isEmpty()) {
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureExtensionIsMutable();
            extension_.addAll(other.extension_);
          }
          onChanged();
        }
      } else {
        if (!other.extension_.isEmpty()) {
          if (extensionBuilder_.isEmpty()) {
            extensionBuilder_.dispose();
            extensionBuilder_ = null;
            extension_ = other.extension_;
            bitField0_ = (bitField0_ & ~0x00000010);
            extensionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtensionFieldBuilder() : null;
          } else {
            extensionBuilder_.addAllMessages(other.extension_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.paolu.xray.core.InboundHandlerConfig m =
                  input.readMessage(
                      cloud.paolu.xray.core.InboundHandlerConfig.parser(),
                      extensionRegistry);
              if (inboundBuilder_ == null) {
                ensureInboundIsMutable();
                inbound_.add(m);
              } else {
                inboundBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              cloud.paolu.xray.core.OutboundHandlerConfig m =
                  input.readMessage(
                      cloud.paolu.xray.core.OutboundHandlerConfig.parser(),
                      extensionRegistry);
              if (outboundBuilder_ == null) {
                ensureOutboundIsMutable();
                outbound_.add(m);
              } else {
                outboundBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 34: {
              cloud.paolu.xray.common.serial.TypedMessage m =
                  input.readMessage(
                      cloud.paolu.xray.common.serial.TypedMessage.parser(),
                      extensionRegistry);
              if (appBuilder_ == null) {
                ensureAppIsMutable();
                app_.add(m);
              } else {
                appBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getTransportFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            case 50: {
              cloud.paolu.xray.common.serial.TypedMessage m =
                  input.readMessage(
                      cloud.paolu.xray.common.serial.TypedMessage.parser(),
                      extensionRegistry);
              if (extensionBuilder_ == null) {
                ensureExtensionIsMutable();
                extension_.add(m);
              } else {
                extensionBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.paolu.xray.core.InboundHandlerConfig> inbound_ =
      java.util.Collections.emptyList();
    private void ensureInboundIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        inbound_ = new java.util.ArrayList<cloud.paolu.xray.core.InboundHandlerConfig>(inbound_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.core.InboundHandlerConfig, cloud.paolu.xray.core.InboundHandlerConfig.Builder, cloud.paolu.xray.core.InboundHandlerConfigOrBuilder> inboundBuilder_;

    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public java.util.List<cloud.paolu.xray.core.InboundHandlerConfig> getInboundList() {
      if (inboundBuilder_ == null) {
        return java.util.Collections.unmodifiableList(inbound_);
      } else {
        return inboundBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public int getInboundCount() {
      if (inboundBuilder_ == null) {
        return inbound_.size();
      } else {
        return inboundBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public cloud.paolu.xray.core.InboundHandlerConfig getInbound(int index) {
      if (inboundBuilder_ == null) {
        return inbound_.get(index);
      } else {
        return inboundBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder setInbound(
        int index, cloud.paolu.xray.core.InboundHandlerConfig value) {
      if (inboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboundIsMutable();
        inbound_.set(index, value);
        onChanged();
      } else {
        inboundBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder setInbound(
        int index, cloud.paolu.xray.core.InboundHandlerConfig.Builder builderForValue) {
      if (inboundBuilder_ == null) {
        ensureInboundIsMutable();
        inbound_.set(index, builderForValue.build());
        onChanged();
      } else {
        inboundBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder addInbound(cloud.paolu.xray.core.InboundHandlerConfig value) {
      if (inboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboundIsMutable();
        inbound_.add(value);
        onChanged();
      } else {
        inboundBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder addInbound(
        int index, cloud.paolu.xray.core.InboundHandlerConfig value) {
      if (inboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboundIsMutable();
        inbound_.add(index, value);
        onChanged();
      } else {
        inboundBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder addInbound(
        cloud.paolu.xray.core.InboundHandlerConfig.Builder builderForValue) {
      if (inboundBuilder_ == null) {
        ensureInboundIsMutable();
        inbound_.add(builderForValue.build());
        onChanged();
      } else {
        inboundBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder addInbound(
        int index, cloud.paolu.xray.core.InboundHandlerConfig.Builder builderForValue) {
      if (inboundBuilder_ == null) {
        ensureInboundIsMutable();
        inbound_.add(index, builderForValue.build());
        onChanged();
      } else {
        inboundBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder addAllInbound(
        java.lang.Iterable<? extends cloud.paolu.xray.core.InboundHandlerConfig> values) {
      if (inboundBuilder_ == null) {
        ensureInboundIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inbound_);
        onChanged();
      } else {
        inboundBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder clearInbound() {
      if (inboundBuilder_ == null) {
        inbound_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        inboundBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public Builder removeInbound(int index) {
      if (inboundBuilder_ == null) {
        ensureInboundIsMutable();
        inbound_.remove(index);
        onChanged();
      } else {
        inboundBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public cloud.paolu.xray.core.InboundHandlerConfig.Builder getInboundBuilder(
        int index) {
      return getInboundFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public cloud.paolu.xray.core.InboundHandlerConfigOrBuilder getInboundOrBuilder(
        int index) {
      if (inboundBuilder_ == null) {
        return inbound_.get(index);  } else {
        return inboundBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.core.InboundHandlerConfigOrBuilder> 
         getInboundOrBuilderList() {
      if (inboundBuilder_ != null) {
        return inboundBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(inbound_);
      }
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public cloud.paolu.xray.core.InboundHandlerConfig.Builder addInboundBuilder() {
      return getInboundFieldBuilder().addBuilder(
          cloud.paolu.xray.core.InboundHandlerConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public cloud.paolu.xray.core.InboundHandlerConfig.Builder addInboundBuilder(
        int index) {
      return getInboundFieldBuilder().addBuilder(
          index, cloud.paolu.xray.core.InboundHandlerConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Inbound handler configurations. Must have at least one item.
     * </pre>
     *
     * <code>repeated .xray.core.InboundHandlerConfig inbound = 1;</code>
     */
    public java.util.List<cloud.paolu.xray.core.InboundHandlerConfig.Builder> 
         getInboundBuilderList() {
      return getInboundFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.core.InboundHandlerConfig, cloud.paolu.xray.core.InboundHandlerConfig.Builder, cloud.paolu.xray.core.InboundHandlerConfigOrBuilder> 
        getInboundFieldBuilder() {
      if (inboundBuilder_ == null) {
        inboundBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.core.InboundHandlerConfig, cloud.paolu.xray.core.InboundHandlerConfig.Builder, cloud.paolu.xray.core.InboundHandlerConfigOrBuilder>(
                inbound_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        inbound_ = null;
      }
      return inboundBuilder_;
    }

    private java.util.List<cloud.paolu.xray.core.OutboundHandlerConfig> outbound_ =
      java.util.Collections.emptyList();
    private void ensureOutboundIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        outbound_ = new java.util.ArrayList<cloud.paolu.xray.core.OutboundHandlerConfig>(outbound_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.core.OutboundHandlerConfig, cloud.paolu.xray.core.OutboundHandlerConfig.Builder, cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder> outboundBuilder_;

    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public java.util.List<cloud.paolu.xray.core.OutboundHandlerConfig> getOutboundList() {
      if (outboundBuilder_ == null) {
        return java.util.Collections.unmodifiableList(outbound_);
      } else {
        return outboundBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public int getOutboundCount() {
      if (outboundBuilder_ == null) {
        return outbound_.size();
      } else {
        return outboundBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public cloud.paolu.xray.core.OutboundHandlerConfig getOutbound(int index) {
      if (outboundBuilder_ == null) {
        return outbound_.get(index);
      } else {
        return outboundBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder setOutbound(
        int index, cloud.paolu.xray.core.OutboundHandlerConfig value) {
      if (outboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutboundIsMutable();
        outbound_.set(index, value);
        onChanged();
      } else {
        outboundBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder setOutbound(
        int index, cloud.paolu.xray.core.OutboundHandlerConfig.Builder builderForValue) {
      if (outboundBuilder_ == null) {
        ensureOutboundIsMutable();
        outbound_.set(index, builderForValue.build());
        onChanged();
      } else {
        outboundBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder addOutbound(cloud.paolu.xray.core.OutboundHandlerConfig value) {
      if (outboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutboundIsMutable();
        outbound_.add(value);
        onChanged();
      } else {
        outboundBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder addOutbound(
        int index, cloud.paolu.xray.core.OutboundHandlerConfig value) {
      if (outboundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutboundIsMutable();
        outbound_.add(index, value);
        onChanged();
      } else {
        outboundBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder addOutbound(
        cloud.paolu.xray.core.OutboundHandlerConfig.Builder builderForValue) {
      if (outboundBuilder_ == null) {
        ensureOutboundIsMutable();
        outbound_.add(builderForValue.build());
        onChanged();
      } else {
        outboundBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder addOutbound(
        int index, cloud.paolu.xray.core.OutboundHandlerConfig.Builder builderForValue) {
      if (outboundBuilder_ == null) {
        ensureOutboundIsMutable();
        outbound_.add(index, builderForValue.build());
        onChanged();
      } else {
        outboundBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder addAllOutbound(
        java.lang.Iterable<? extends cloud.paolu.xray.core.OutboundHandlerConfig> values) {
      if (outboundBuilder_ == null) {
        ensureOutboundIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outbound_);
        onChanged();
      } else {
        outboundBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder clearOutbound() {
      if (outboundBuilder_ == null) {
        outbound_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        outboundBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public Builder removeOutbound(int index) {
      if (outboundBuilder_ == null) {
        ensureOutboundIsMutable();
        outbound_.remove(index);
        onChanged();
      } else {
        outboundBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public cloud.paolu.xray.core.OutboundHandlerConfig.Builder getOutboundBuilder(
        int index) {
      return getOutboundFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder getOutboundOrBuilder(
        int index) {
      if (outboundBuilder_ == null) {
        return outbound_.get(index);  } else {
        return outboundBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder> 
         getOutboundOrBuilderList() {
      if (outboundBuilder_ != null) {
        return outboundBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(outbound_);
      }
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public cloud.paolu.xray.core.OutboundHandlerConfig.Builder addOutboundBuilder() {
      return getOutboundFieldBuilder().addBuilder(
          cloud.paolu.xray.core.OutboundHandlerConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public cloud.paolu.xray.core.OutboundHandlerConfig.Builder addOutboundBuilder(
        int index) {
      return getOutboundFieldBuilder().addBuilder(
          index, cloud.paolu.xray.core.OutboundHandlerConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Outbound handler configurations. Must have at least one item. The first
     * item is used as default for routing.
     * </pre>
     *
     * <code>repeated .xray.core.OutboundHandlerConfig outbound = 2;</code>
     */
    public java.util.List<cloud.paolu.xray.core.OutboundHandlerConfig.Builder> 
         getOutboundBuilderList() {
      return getOutboundFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.core.OutboundHandlerConfig, cloud.paolu.xray.core.OutboundHandlerConfig.Builder, cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder> 
        getOutboundFieldBuilder() {
      if (outboundBuilder_ == null) {
        outboundBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.core.OutboundHandlerConfig, cloud.paolu.xray.core.OutboundHandlerConfig.Builder, cloud.paolu.xray.core.OutboundHandlerConfigOrBuilder>(
                outbound_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        outbound_ = null;
      }
      return outboundBuilder_;
    }

    private java.util.List<cloud.paolu.xray.common.serial.TypedMessage> app_ =
      java.util.Collections.emptyList();
    private void ensureAppIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        app_ = new java.util.ArrayList<cloud.paolu.xray.common.serial.TypedMessage>(app_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder> appBuilder_;

    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public java.util.List<cloud.paolu.xray.common.serial.TypedMessage> getAppList() {
      if (appBuilder_ == null) {
        return java.util.Collections.unmodifiableList(app_);
      } else {
        return appBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public int getAppCount() {
      if (appBuilder_ == null) {
        return app_.size();
      } else {
        return appBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage getApp(int index) {
      if (appBuilder_ == null) {
        return app_.get(index);
      } else {
        return appBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder setApp(
        int index, cloud.paolu.xray.common.serial.TypedMessage value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppIsMutable();
        app_.set(index, value);
        onChanged();
      } else {
        appBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder setApp(
        int index, cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (appBuilder_ == null) {
        ensureAppIsMutable();
        app_.set(index, builderForValue.build());
        onChanged();
      } else {
        appBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder addApp(cloud.paolu.xray.common.serial.TypedMessage value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppIsMutable();
        app_.add(value);
        onChanged();
      } else {
        appBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder addApp(
        int index, cloud.paolu.xray.common.serial.TypedMessage value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppIsMutable();
        app_.add(index, value);
        onChanged();
      } else {
        appBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder addApp(
        cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (appBuilder_ == null) {
        ensureAppIsMutable();
        app_.add(builderForValue.build());
        onChanged();
      } else {
        appBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder addApp(
        int index, cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (appBuilder_ == null) {
        ensureAppIsMutable();
        app_.add(index, builderForValue.build());
        onChanged();
      } else {
        appBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder addAllApp(
        java.lang.Iterable<? extends cloud.paolu.xray.common.serial.TypedMessage> values) {
      if (appBuilder_ == null) {
        ensureAppIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, app_);
        onChanged();
      } else {
        appBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder clearApp() {
      if (appBuilder_ == null) {
        app_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        appBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public Builder removeApp(int index) {
      if (appBuilder_ == null) {
        ensureAppIsMutable();
        app_.remove(index);
        onChanged();
      } else {
        appBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder getAppBuilder(
        int index) {
      return getAppFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessageOrBuilder getAppOrBuilder(
        int index) {
      if (appBuilder_ == null) {
        return app_.get(index);  } else {
        return appBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
         getAppOrBuilderList() {
      if (appBuilder_ != null) {
        return appBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(app_);
      }
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder addAppBuilder() {
      return getAppFieldBuilder().addBuilder(
          cloud.paolu.xray.common.serial.TypedMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder addAppBuilder(
        int index) {
      return getAppFieldBuilder().addBuilder(
          index, cloud.paolu.xray.common.serial.TypedMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * App is for configurations of all features in Xray. A feature must
     * implement the Feature interface, and its config type must be registered
     * through common.RegisterConfig.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage app = 4;</code>
     */
    public java.util.List<cloud.paolu.xray.common.serial.TypedMessage.Builder> 
         getAppBuilderList() {
      return getAppFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
        getAppFieldBuilder() {
      if (appBuilder_ == null) {
        appBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder>(
                app_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        app_ = null;
      }
      return appBuilder_;
    }

    private cloud.paolu.xray.transport.global.Config transport_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.global.Config, cloud.paolu.xray.transport.global.Config.Builder, cloud.paolu.xray.transport.global.ConfigOrBuilder> transportBuilder_;
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     * @deprecated xray.core.Config.transport is deprecated.
     *     See core/config.proto;l=31
     * @return Whether the transport field is set.
     */
    @java.lang.Deprecated public boolean hasTransport() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     * @deprecated xray.core.Config.transport is deprecated.
     *     See core/config.proto;l=31
     * @return The transport.
     */
    @java.lang.Deprecated public cloud.paolu.xray.transport.global.Config getTransport() {
      if (transportBuilder_ == null) {
        return transport_ == null ? cloud.paolu.xray.transport.global.Config.getDefaultInstance() : transport_;
      } else {
        return transportBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setTransport(cloud.paolu.xray.transport.global.Config value) {
      if (transportBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transport_ = value;
      } else {
        transportBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setTransport(
        cloud.paolu.xray.transport.global.Config.Builder builderForValue) {
      if (transportBuilder_ == null) {
        transport_ = builderForValue.build();
      } else {
        transportBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder mergeTransport(cloud.paolu.xray.transport.global.Config value) {
      if (transportBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          transport_ != null &&
          transport_ != cloud.paolu.xray.transport.global.Config.getDefaultInstance()) {
          getTransportBuilder().mergeFrom(value);
        } else {
          transport_ = value;
        }
      } else {
        transportBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearTransport() {
      bitField0_ = (bitField0_ & ~0x00000008);
      transport_ = null;
      if (transportBuilder_ != null) {
        transportBuilder_.dispose();
        transportBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public cloud.paolu.xray.transport.global.Config.Builder getTransportBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTransportFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    @java.lang.Deprecated public cloud.paolu.xray.transport.global.ConfigOrBuilder getTransportOrBuilder() {
      if (transportBuilder_ != null) {
        return transportBuilder_.getMessageOrBuilder();
      } else {
        return transport_ == null ?
            cloud.paolu.xray.transport.global.Config.getDefaultInstance() : transport_;
      }
    }
    /**
     * <pre>
     * Transport settings.
     * Deprecated. Each inbound and outbound should choose their own transport
     * config. Date to remove: 2020-01-13
     * </pre>
     *
     * <code>.xray.transport.Config transport = 5 [deprecated = true];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cloud.paolu.xray.transport.global.Config, cloud.paolu.xray.transport.global.Config.Builder, cloud.paolu.xray.transport.global.ConfigOrBuilder> 
        getTransportFieldBuilder() {
      if (transportBuilder_ == null) {
        transportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cloud.paolu.xray.transport.global.Config, cloud.paolu.xray.transport.global.Config.Builder, cloud.paolu.xray.transport.global.ConfigOrBuilder>(
                getTransport(),
                getParentForChildren(),
                isClean());
        transport_ = null;
      }
      return transportBuilder_;
    }

    private java.util.List<cloud.paolu.xray.common.serial.TypedMessage> extension_ =
      java.util.Collections.emptyList();
    private void ensureExtensionIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        extension_ = new java.util.ArrayList<cloud.paolu.xray.common.serial.TypedMessage>(extension_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder> extensionBuilder_;

    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public java.util.List<cloud.paolu.xray.common.serial.TypedMessage> getExtensionList() {
      if (extensionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extension_);
      } else {
        return extensionBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public int getExtensionCount() {
      if (extensionBuilder_ == null) {
        return extension_.size();
      } else {
        return extensionBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage getExtension(int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);
      } else {
        return extensionBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder setExtension(
        int index, cloud.paolu.xray.common.serial.TypedMessage value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.set(index, value);
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder setExtension(
        int index, cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.set(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder addExtension(cloud.paolu.xray.common.serial.TypedMessage value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder addExtension(
        int index, cloud.paolu.xray.common.serial.TypedMessage value) {
      if (extensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionIsMutable();
        extension_.add(index, value);
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder addExtension(
        cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder addExtension(
        int index, cloud.paolu.xray.common.serial.TypedMessage.Builder builderForValue) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.add(index, builderForValue.build());
        onChanged();
      } else {
        extensionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder addAllExtension(
        java.lang.Iterable<? extends cloud.paolu.xray.common.serial.TypedMessage> values) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extension_);
        onChanged();
      } else {
        extensionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder clearExtension() {
      if (extensionBuilder_ == null) {
        extension_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        extensionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public Builder removeExtension(int index) {
      if (extensionBuilder_ == null) {
        ensureExtensionIsMutable();
        extension_.remove(index);
        onChanged();
      } else {
        extensionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder getExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessageOrBuilder getExtensionOrBuilder(
        int index) {
      if (extensionBuilder_ == null) {
        return extension_.get(index);  } else {
        return extensionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public java.util.List<? extends cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
         getExtensionOrBuilderList() {
      if (extensionBuilder_ != null) {
        return extensionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extension_);
      }
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder addExtensionBuilder() {
      return getExtensionFieldBuilder().addBuilder(
          cloud.paolu.xray.common.serial.TypedMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public cloud.paolu.xray.common.serial.TypedMessage.Builder addExtensionBuilder(
        int index) {
      return getExtensionFieldBuilder().addBuilder(
          index, cloud.paolu.xray.common.serial.TypedMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * Configuration for extensions. The config may not work if corresponding
     * extension is not loaded into Xray. Xray will ignore such config during
     * initialization.
     * </pre>
     *
     * <code>repeated .xray.common.serial.TypedMessage extension = 6;</code>
     */
    public java.util.List<cloud.paolu.xray.common.serial.TypedMessage.Builder> 
         getExtensionBuilderList() {
      return getExtensionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder> 
        getExtensionFieldBuilder() {
      if (extensionBuilder_ == null) {
        extensionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cloud.paolu.xray.common.serial.TypedMessage, cloud.paolu.xray.common.serial.TypedMessage.Builder, cloud.paolu.xray.common.serial.TypedMessageOrBuilder>(
                extension_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        extension_ = null;
      }
      return extensionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.core.Config)
  }

  // @@protoc_insertion_point(class_scope:xray.core.Config)
  private static final cloud.paolu.xray.core.Config DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.paolu.xray.core.Config();
  }

  public static cloud.paolu.xray.core.Config getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Config>
      PARSER = new com.google.protobuf.AbstractParser<Config>() {
    @java.lang.Override
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Config> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.paolu.xray.core.Config getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

