// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package cloud.paolu.xray.transport.internet;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_TransportConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_TransportConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_StreamConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_StreamConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_ProxyConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_ProxyConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_SocketConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037transport/internet/config.proto\022\027xray." +
      "transport.internet\032!common/serial/typed_" +
      "message.proto\"\236\001\n\017TransportConfig\022@\n\010pro" +
      "tocol\030\001 \001(\0162*.xray.transport.internet.Tr" +
      "ansportProtocolB\002\030\001\022\025\n\rprotocol_name\030\003 \001" +
      "(\t\0222\n\010settings\030\002 \001(\0132 .xray.common.seria" +
      "l.TypedMessage\"\301\002\n\014StreamConfig\022@\n\010proto" +
      "col\030\001 \001(\0162*.xray.transport.internet.Tran" +
      "sportProtocolB\002\030\001\022\025\n\rprotocol_name\030\005 \001(\t" +
      "\022D\n\022transport_settings\030\002 \003(\0132(.xray.tran" +
      "sport.internet.TransportConfig\022\025\n\rsecuri" +
      "ty_type\030\003 \001(\t\022;\n\021security_settings\030\004 \003(\013" +
      "2 .xray.common.serial.TypedMessage\022>\n\017so" +
      "cket_settings\030\006 \001(\0132%.xray.transport.int" +
      "ernet.SocketConfig\"7\n\013ProxyConfig\022\013\n\003tag" +
      "\030\001 \001(\t\022\033\n\023transportLayerProxy\030\002 \001(\010\"\273\004\n\014" +
      "SocketConfig\022\014\n\004mark\030\001 \001(\005\022\013\n\003tfo\030\002 \001(\005\022" +
      "@\n\006tproxy\030\003 \001(\01620.xray.transport.interne" +
      "t.SocketConfig.TProxyMode\022%\n\035receive_ori" +
      "ginal_dest_address\030\004 \001(\010\022\024\n\014bind_address" +
      "\030\005 \001(\014\022\021\n\tbind_port\030\006 \001(\r\022\035\n\025accept_prox" +
      "y_protocol\030\007 \001(\010\022@\n\017domain_strategy\030\010 \001(" +
      "\0162\'.xray.transport.internet.DomainStrate" +
      "gy\022\024\n\014dialer_proxy\030\t \001(\t\022\037\n\027tcp_keep_ali" +
      "ve_interval\030\n \001(\005\022\033\n\023tcp_keep_alive_idle" +
      "\030\013 \001(\005\022\026\n\016tcp_congestion\030\014 \001(\t\022\021\n\tinterf" +
      "ace\030\r \001(\t\022\016\n\006v6only\030\016 \001(\010\022\030\n\020tcp_window_" +
      "clamp\030\017 \001(\005\022\030\n\020tcp_user_timeout\030\020 \001(\005\022\023\n" +
      "\013tcp_max_seg\030\021 \001(\005\022\024\n\014tcp_no_delay\030\022 \001(\010" +
      "\"/\n\nTProxyMode\022\007\n\003Off\020\000\022\n\n\006TProxy\020\001\022\014\n\010R" +
      "edirect\020\002*Z\n\021TransportProtocol\022\007\n\003TCP\020\000\022" +
      "\007\n\003UDP\020\001\022\010\n\004MKCP\020\002\022\r\n\tWebSocket\020\003\022\010\n\004HTT" +
      "P\020\004\022\020\n\014DomainSocket\020\005*A\n\016DomainStrategy\022" +
      "\t\n\005AS_IS\020\000\022\n\n\006USE_IP\020\001\022\013\n\007USE_IP4\020\002\022\013\n\007U" +
      "SE_IP6\020\003Bo\n#cloud.paolu.xray.transport.i" +
      "nternetP\001Z,github.com/xtls/xray-core/tra" +
      "nsport/internet\252\002\027Xray.Transport.Interne" +
      "tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
        });
    internal_static_xray_transport_internet_TransportConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_TransportConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_TransportConfig_descriptor,
        new java.lang.String[] { "Protocol", "ProtocolName", "Settings", });
    internal_static_xray_transport_internet_StreamConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_transport_internet_StreamConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_StreamConfig_descriptor,
        new java.lang.String[] { "Protocol", "ProtocolName", "TransportSettings", "SecurityType", "SecuritySettings", "SocketSettings", });
    internal_static_xray_transport_internet_ProxyConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xray_transport_internet_ProxyConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_ProxyConfig_descriptor,
        new java.lang.String[] { "Tag", "TransportLayerProxy", });
    internal_static_xray_transport_internet_SocketConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_SocketConfig_descriptor,
        new java.lang.String[] { "Mark", "Tfo", "Tproxy", "ReceiveOriginalDestAddress", "BindAddress", "BindPort", "AcceptProxyProtocol", "DomainStrategy", "DialerProxy", "TcpKeepAliveInterval", "TcpKeepAliveIdle", "TcpCongestion", "Interface", "V6Only", "TcpWindowClamp", "TcpUserTimeout", "TcpMaxSeg", "TcpNoDelay", });
    cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
