// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/global/config.proto

package cloud.paolu.xray.transport.global;

@java.lang.Deprecated public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.transport.internet.TransportConfig transport_settings = 1;</code>
   */
  java.util.List<cloud.paolu.xray.transport.internet.TransportConfig> 
      getTransportSettingsList();
  /**
   * <code>repeated .xray.transport.internet.TransportConfig transport_settings = 1;</code>
   */
  cloud.paolu.xray.transport.internet.TransportConfig getTransportSettings(int index);
  /**
   * <code>repeated .xray.transport.internet.TransportConfig transport_settings = 1;</code>
   */
  int getTransportSettingsCount();
  /**
   * <code>repeated .xray.transport.internet.TransportConfig transport_settings = 1;</code>
   */
  java.util.List<? extends cloud.paolu.xray.transport.internet.TransportConfigOrBuilder> 
      getTransportSettingsOrBuilderList();
  /**
   * <code>repeated .xray.transport.internet.TransportConfig transport_settings = 1;</code>
   */
  cloud.paolu.xray.transport.internet.TransportConfigOrBuilder getTransportSettingsOrBuilder(
      int index);
}
