// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/observatory/command/command.proto

package cloud.paolu.xray.core.app.observatory.command;

public interface GetOutboundStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.core.app.observatory.command.GetOutboundStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.core.app.observatory.ObservationResult status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.xray.core.app.observatory.ObservationResult status = 1;</code>
   * @return The status.
   */
  cloud.paolu.xray.app.observatory.ObservationResult getStatus();
  /**
   * <code>.xray.core.app.observatory.ObservationResult status = 1;</code>
   */
  cloud.paolu.xray.app.observatory.ObservationResultOrBuilder getStatusOrBuilder();
}
