// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/headers/wechat/config.proto

package cloud.paolu.xray.transport.internet.headers.wechat;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_transport_internet_headers_wechat_VideoConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_transport_internet_headers_wechat_VideoConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.transport/internet/headers/wechat/conf" +
      "ig.proto\022&xray.transport.internet.header" +
      "s.wechat\"\r\n\013VideoConfigB\234\001\n2cloud.paolu." +
      "xray.transport.internet.headers.wechatP\001" +
      "Z;github.com/xtls/xray-core/transport/in" +
      "ternet/headers/wechat\252\002&Xray.Transport.I" +
      "nternet.Headers.Wechatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xray_transport_internet_headers_wechat_VideoConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_transport_internet_headers_wechat_VideoConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_transport_internet_headers_wechat_VideoConfig_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
