// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/reverse/config.proto

package cloud.paolu.xray.proxy.reverse;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.reverse.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.app.reverse.BridgeConfig bridge_config = 1;</code>
   */
  java.util.List<cloud.paolu.xray.proxy.reverse.BridgeConfig> 
      getBridgeConfigList();
  /**
   * <code>repeated .xray.app.reverse.BridgeConfig bridge_config = 1;</code>
   */
  cloud.paolu.xray.proxy.reverse.BridgeConfig getBridgeConfig(int index);
  /**
   * <code>repeated .xray.app.reverse.BridgeConfig bridge_config = 1;</code>
   */
  int getBridgeConfigCount();
  /**
   * <code>repeated .xray.app.reverse.BridgeConfig bridge_config = 1;</code>
   */
  java.util.List<? extends cloud.paolu.xray.proxy.reverse.BridgeConfigOrBuilder> 
      getBridgeConfigOrBuilderList();
  /**
   * <code>repeated .xray.app.reverse.BridgeConfig bridge_config = 1;</code>
   */
  cloud.paolu.xray.proxy.reverse.BridgeConfigOrBuilder getBridgeConfigOrBuilder(
      int index);

  /**
   * <code>repeated .xray.app.reverse.PortalConfig portal_config = 2;</code>
   */
  java.util.List<cloud.paolu.xray.proxy.reverse.PortalConfig> 
      getPortalConfigList();
  /**
   * <code>repeated .xray.app.reverse.PortalConfig portal_config = 2;</code>
   */
  cloud.paolu.xray.proxy.reverse.PortalConfig getPortalConfig(int index);
  /**
   * <code>repeated .xray.app.reverse.PortalConfig portal_config = 2;</code>
   */
  int getPortalConfigCount();
  /**
   * <code>repeated .xray.app.reverse.PortalConfig portal_config = 2;</code>
   */
  java.util.List<? extends cloud.paolu.xray.proxy.reverse.PortalConfigOrBuilder> 
      getPortalConfigOrBuilderList();
  /**
   * <code>repeated .xray.app.reverse.PortalConfig portal_config = 2;</code>
   */
  cloud.paolu.xray.proxy.reverse.PortalConfigOrBuilder getPortalConfigOrBuilder(
      int index);
}
