// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/tls/config.proto

package cloud.paolu.xray.transport.internet.tls;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.transport.internet.tls.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether or not to allow self-signed certificates.
   * </pre>
   *
   * <code>bool allow_insecure = 1;</code>
   * @return The allowInsecure.
   */
  boolean getAllowInsecure();

  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
   */
  java.util.List<cloud.paolu.xray.transport.internet.tls.Certificate> 
      getCertificateList();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
   */
  cloud.paolu.xray.transport.internet.tls.Certificate getCertificate(int index);
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
   */
  int getCertificateCount();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
   */
  java.util.List<? extends cloud.paolu.xray.transport.internet.tls.CertificateOrBuilder> 
      getCertificateOrBuilderList();
  /**
   * <pre>
   * List of certificates to be served on server.
   * </pre>
   *
   * <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
   */
  cloud.paolu.xray.transport.internet.tls.CertificateOrBuilder getCertificateOrBuilder(
      int index);

  /**
   * <pre>
   * Override server name.
   * </pre>
   *
   * <code>string server_name = 3;</code>
   * @return The serverName.
   */
  java.lang.String getServerName();
  /**
   * <pre>
   * Override server name.
   * </pre>
   *
   * <code>string server_name = 3;</code>
   * @return The bytes for serverName.
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   * @return A list containing the nextProtocol.
   */
  java.util.List<java.lang.String>
      getNextProtocolList();
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   * @return The count of nextProtocol.
   */
  int getNextProtocolCount();
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   * @param index The index of the element to return.
   * @return The nextProtocol at the given index.
   */
  java.lang.String getNextProtocol(int index);
  /**
   * <pre>
   * Lists of string as ALPN values.
   * </pre>
   *
   * <code>repeated string next_protocol = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the nextProtocol at the given index.
   */
  com.google.protobuf.ByteString
      getNextProtocolBytes(int index);

  /**
   * <pre>
   * Whether or not to enable session (ticket) resumption.
   * </pre>
   *
   * <code>bool enable_session_resumption = 5;</code>
   * @return The enableSessionResumption.
   */
  boolean getEnableSessionResumption();

  /**
   * <pre>
   * If true, root certificates on the system will not be loaded for
   * verification.
   * </pre>
   *
   * <code>bool disable_system_root = 6;</code>
   * @return The disableSystemRoot.
   */
  boolean getDisableSystemRoot();

  /**
   * <pre>
   * The minimum TLS version.
   * </pre>
   *
   * <code>string min_version = 7;</code>
   * @return The minVersion.
   */
  java.lang.String getMinVersion();
  /**
   * <pre>
   * The minimum TLS version.
   * </pre>
   *
   * <code>string min_version = 7;</code>
   * @return The bytes for minVersion.
   */
  com.google.protobuf.ByteString
      getMinVersionBytes();

  /**
   * <pre>
   * The maximum TLS version.
   * </pre>
   *
   * <code>string max_version = 8;</code>
   * @return The maxVersion.
   */
  java.lang.String getMaxVersion();
  /**
   * <pre>
   * The maximum TLS version.
   * </pre>
   *
   * <code>string max_version = 8;</code>
   * @return The bytes for maxVersion.
   */
  com.google.protobuf.ByteString
      getMaxVersionBytes();

  /**
   * <pre>
   * Specify cipher suites, except for TLS 1.3.
   * </pre>
   *
   * <code>string cipher_suites = 9;</code>
   * @return The cipherSuites.
   */
  java.lang.String getCipherSuites();
  /**
   * <pre>
   * Specify cipher suites, except for TLS 1.3.
   * </pre>
   *
   * <code>string cipher_suites = 9;</code>
   * @return The bytes for cipherSuites.
   */
  com.google.protobuf.ByteString
      getCipherSuitesBytes();

  /**
   * <pre>
   * Whether the server selects its most preferred ciphersuite.
   * </pre>
   *
   * <code>bool prefer_server_cipher_suites = 10;</code>
   * @return The preferServerCipherSuites.
   */
  boolean getPreferServerCipherSuites();

  /**
   * <pre>
   * TLS Client Hello fingerprint (uTLS).
   * </pre>
   *
   * <code>string fingerprint = 11;</code>
   * @return The fingerprint.
   */
  java.lang.String getFingerprint();
  /**
   * <pre>
   * TLS Client Hello fingerprint (uTLS).
   * </pre>
   *
   * <code>string fingerprint = 11;</code>
   * @return The bytes for fingerprint.
   */
  com.google.protobuf.ByteString
      getFingerprintBytes();

  /**
   * <code>bool reject_unknown_sni = 12;</code>
   * @return The rejectUnknownSni.
   */
  boolean getRejectUnknownSni();

  /**
   * <pre>
   * &#64;Document A pinned certificate chain sha256 hash.
   *&#64;Document If the server's hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_chain_sha256 = 13;</code>
   * @return A list containing the pinnedPeerCertificateChainSha256.
   */
  java.util.List<com.google.protobuf.ByteString> getPinnedPeerCertificateChainSha256List();
  /**
   * <pre>
   * &#64;Document A pinned certificate chain sha256 hash.
   *&#64;Document If the server's hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_chain_sha256 = 13;</code>
   * @return The count of pinnedPeerCertificateChainSha256.
   */
  int getPinnedPeerCertificateChainSha256Count();
  /**
   * <pre>
   * &#64;Document A pinned certificate chain sha256 hash.
   *&#64;Document If the server's hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_chain_sha256 = 13;</code>
   * @param index The index of the element to return.
   * @return The pinnedPeerCertificateChainSha256 at the given index.
   */
  com.google.protobuf.ByteString getPinnedPeerCertificateChainSha256(int index);

  /**
   * <pre>
   * &#64;Document A pinned certificate public key sha256 hash.
   *&#64;Document If the server's public key hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_public_key_sha256 = 14;</code>
   * @return A list containing the pinnedPeerCertificatePublicKeySha256.
   */
  java.util.List<com.google.protobuf.ByteString> getPinnedPeerCertificatePublicKeySha256List();
  /**
   * <pre>
   * &#64;Document A pinned certificate public key sha256 hash.
   *&#64;Document If the server's public key hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_public_key_sha256 = 14;</code>
   * @return The count of pinnedPeerCertificatePublicKeySha256.
   */
  int getPinnedPeerCertificatePublicKeySha256Count();
  /**
   * <pre>
   * &#64;Document A pinned certificate public key sha256 hash.
   *&#64;Document If the server's public key hash does not match this value, the connection will be aborted.
   *&#64;Document This value replace allow_insecure.
   *&#64;Critical
   * </pre>
   *
   * <code>repeated bytes pinned_peer_certificate_public_key_sha256 = 14;</code>
   * @param index The index of the element to return.
   * @return The pinnedPeerCertificatePublicKeySha256 at the given index.
   */
  com.google.protobuf.ByteString getPinnedPeerCertificatePublicKeySha256(int index);
}
