// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/dispatcher/config.proto

package cloud.paolu.xray.app.dispatcher;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.dispatcher.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.xray.app.dispatcher.SessionConfig settings = 1;</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <code>.xray.app.dispatcher.SessionConfig settings = 1;</code>
   * @return The settings.
   */
  cloud.paolu.xray.app.dispatcher.SessionConfig getSettings();
  /**
   * <code>.xray.app.dispatcher.SessionConfig settings = 1;</code>
   */
  cloud.paolu.xray.app.dispatcher.SessionConfigOrBuilder getSettingsOrBuilder();
}
