// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/inbound/config.proto

package cloud.paolu.xray.proxy.vmess.inbound;

public interface DefaultConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.proxy.vmess.inbound.DefaultConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 level = 2;</code>
   * @return The level.
   */
  int getLevel();
}
