// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/config.proto

package cloud.paolu.xray.app.router;

public interface GeoSiteListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.GeoSiteList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xray.app.router.GeoSite entry = 1;</code>
   */
  java.util.List<cloud.paolu.xray.app.router.GeoSite> 
      getEntryList();
  /**
   * <code>repeated .xray.app.router.GeoSite entry = 1;</code>
   */
  cloud.paolu.xray.app.router.GeoSite getEntry(int index);
  /**
   * <code>repeated .xray.app.router.GeoSite entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .xray.app.router.GeoSite entry = 1;</code>
   */
  java.util.List<? extends cloud.paolu.xray.app.router.GeoSiteOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .xray.app.router.GeoSite entry = 1;</code>
   */
  cloud.paolu.xray.app.router.GeoSiteOrBuilder getEntryOrBuilder(
      int index);
}
