// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/config.proto

package cloud.paolu.xray.app.router;

public interface GeoSiteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.router.GeoSite)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  java.util.List<cloud.paolu.xray.app.router.Domain> 
      getDomainList();
  /**
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  cloud.paolu.xray.app.router.Domain getDomain(int index);
  /**
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  int getDomainCount();
  /**
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  java.util.List<? extends cloud.paolu.xray.app.router.DomainOrBuilder> 
      getDomainOrBuilderList();
  /**
   * <code>repeated .xray.app.router.Domain domain = 2;</code>
   */
  cloud.paolu.xray.app.router.DomainOrBuilder getDomainOrBuilder(
      int index);
}
