// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package cloud.paolu.xray.app.proxyman;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_InboundConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_InboundConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_AllocationStrategy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_AllocationStrategy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyConcurrency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyConcurrency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyRefresh_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyRefresh_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_SniffingConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_SniffingConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_ReceiverConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_ReceiverConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_InboundHandlerConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_InboundHandlerConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_OutboundConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_OutboundConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_SenderConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_SenderConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xray_app_proxyman_MultiplexingConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xray_app_proxyman_MultiplexingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031app/proxyman/config.proto\022\021xray.app.pr" +
      "oxyman\032\030common/net/address.proto\032\025common" +
      "/net/port.proto\032\037transport/internet/conf" +
      "ig.proto\032!common/serial/typed_message.pr" +
      "oto\"\017\n\rInboundConfig\"\204\003\n\022AllocationStrat" +
      "egy\0228\n\004type\030\001 \001(\0162*.xray.app.proxyman.Al" +
      "locationStrategy.Type\022X\n\013concurrency\030\002 \001" +
      "(\0132C.xray.app.proxyman.AllocationStrateg" +
      "y.AllocationStrategyConcurrency\022P\n\007refre" +
      "sh\030\003 \001(\0132?.xray.app.proxyman.AllocationS" +
      "trategy.AllocationStrategyRefresh\032.\n\035All" +
      "ocationStrategyConcurrency\022\r\n\005value\030\001 \001(" +
      "\r\032*\n\031AllocationStrategyRefresh\022\r\n\005value\030" +
      "\001 \001(\r\",\n\004Type\022\n\n\006Always\020\000\022\n\n\006Random\020\001\022\014\n" +
      "\010External\020\002\"\204\001\n\016SniffingConfig\022\017\n\007enable" +
      "d\030\001 \001(\010\022\034\n\024destination_override\030\002 \003(\t\022\030\n" +
      "\020domains_excluded\030\003 \003(\t\022\025\n\rmetadata_only" +
      "\030\004 \001(\010\022\022\n\nroute_only\030\005 \001(\010\"\231\003\n\016ReceiverC" +
      "onfig\022,\n\tport_list\030\001 \001(\0132\031.xray.common.n" +
      "et.PortList\022+\n\006listen\030\002 \001(\0132\033.xray.commo" +
      "n.net.IPOrDomain\022B\n\023allocation_strategy\030" +
      "\003 \001(\0132%.xray.app.proxyman.AllocationStra" +
      "tegy\022>\n\017stream_settings\030\004 \001(\0132%.xray.tra" +
      "nsport.internet.StreamConfig\022$\n\034receive_" +
      "original_destination\030\005 \001(\010\022>\n\017domain_ove" +
      "rride\030\007 \003(\0162!.xray.app.proxyman.KnownPro" +
      "tocolsB\002\030\001\022<\n\021sniffing_settings\030\010 \001(\0132!." +
      "xray.app.proxyman.SniffingConfigJ\004\010\006\020\007\"\232" +
      "\001\n\024InboundHandlerConfig\022\013\n\003tag\030\001 \001(\t\022;\n\021" +
      "receiver_settings\030\002 \001(\0132 .xray.common.se" +
      "rial.TypedMessage\0228\n\016proxy_settings\030\003 \001(" +
      "\0132 .xray.common.serial.TypedMessage\"\020\n\016O" +
      "utboundConfig\"\371\001\n\014SenderConfig\022(\n\003via\030\001 " +
      "\001(\0132\033.xray.common.net.IPOrDomain\022>\n\017stre" +
      "am_settings\030\002 \001(\0132%.xray.transport.inter" +
      "net.StreamConfig\022<\n\016proxy_settings\030\003 \001(\013" +
      "2$.xray.transport.internet.ProxyConfig\022A" +
      "\n\022multiplex_settings\030\004 \001(\0132%.xray.app.pr" +
      "oxyman.MultiplexingConfig\"l\n\022Multiplexin" +
      "gConfig\022\017\n\007enabled\030\001 \001(\010\022\023\n\013concurrency\030" +
      "\002 \001(\005\022\027\n\017xudpConcurrency\030\003 \001(\005\022\027\n\017xudpPr" +
      "oxyUDP443\030\004 \001(\t*#\n\016KnownProtocols\022\010\n\004HTT" +
      "P\020\000\022\007\n\003TLS\020\001B]\n\035cloud.paolu.xray.app.pro" +
      "xymanP\001Z&github.com/xtls/xray-core/app/p" +
      "roxyman\252\002\021Xray.App.Proxymanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.paolu.xray.common.net.Address.getDescriptor(),
          cloud.paolu.xray.common.net.Port.getDescriptor(),
          cloud.paolu.xray.transport.internet.Config.getDescriptor(),
          cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
        });
    internal_static_xray_app_proxyman_InboundConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xray_app_proxyman_InboundConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_InboundConfig_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_proxyman_AllocationStrategy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xray_app_proxyman_AllocationStrategy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_AllocationStrategy_descriptor,
        new java.lang.String[] { "Type", "Concurrency", "Refresh", });
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyConcurrency_descriptor =
      internal_static_xray_app_proxyman_AllocationStrategy_descriptor.getNestedTypes().get(0);
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyConcurrency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyConcurrency_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyRefresh_descriptor =
      internal_static_xray_app_proxyman_AllocationStrategy_descriptor.getNestedTypes().get(1);
    internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyRefresh_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_AllocationStrategy_AllocationStrategyRefresh_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_xray_app_proxyman_SniffingConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xray_app_proxyman_SniffingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_SniffingConfig_descriptor,
        new java.lang.String[] { "Enabled", "DestinationOverride", "DomainsExcluded", "MetadataOnly", "RouteOnly", });
    internal_static_xray_app_proxyman_ReceiverConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_xray_app_proxyman_ReceiverConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_ReceiverConfig_descriptor,
        new java.lang.String[] { "PortList", "Listen", "AllocationStrategy", "StreamSettings", "ReceiveOriginalDestination", "DomainOverride", "SniffingSettings", });
    internal_static_xray_app_proxyman_InboundHandlerConfig_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_xray_app_proxyman_InboundHandlerConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_InboundHandlerConfig_descriptor,
        new java.lang.String[] { "Tag", "ReceiverSettings", "ProxySettings", });
    internal_static_xray_app_proxyman_OutboundConfig_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_xray_app_proxyman_OutboundConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_OutboundConfig_descriptor,
        new java.lang.String[] { });
    internal_static_xray_app_proxyman_SenderConfig_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_xray_app_proxyman_SenderConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_SenderConfig_descriptor,
        new java.lang.String[] { "Via", "StreamSettings", "ProxySettings", "MultiplexSettings", });
    internal_static_xray_app_proxyman_MultiplexingConfig_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_xray_app_proxyman_MultiplexingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xray_app_proxyman_MultiplexingConfig_descriptor,
        new java.lang.String[] { "Enabled", "Concurrency", "XudpConcurrency", "XudpProxyUDP443", });
    cloud.paolu.xray.common.net.Address.getDescriptor();
    cloud.paolu.xray.common.net.Port.getDescriptor();
    cloud.paolu.xray.transport.internet.Config.getDescriptor();
    cloud.paolu.xray.common.serial.TypedMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
