// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package cloud.paolu.xray.app.proxyman;

public interface InboundConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.InboundConfig)
    com.google.protobuf.MessageOrBuilder {
}
