// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package cloud.paolu.xray.app.proxyman;

/**
 * Protobuf type {@code xray.app.proxyman.MultiplexingConfig}
 */
public final class MultiplexingConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xray.app.proxyman.MultiplexingConfig)
    MultiplexingConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiplexingConfig.newBuilder() to construct.
  private MultiplexingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiplexingConfig() {
    xudpProxyUDP443_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultiplexingConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.paolu.xray.app.proxyman.Config.internal_static_xray_app_proxyman_MultiplexingConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.paolu.xray.app.proxyman.Config.internal_static_xray_app_proxyman_MultiplexingConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.paolu.xray.app.proxyman.MultiplexingConfig.class, cloud.paolu.xray.app.proxyman.MultiplexingConfig.Builder.class);
  }

  public static final int ENABLED_FIELD_NUMBER = 1;
  private boolean enabled_ = false;
  /**
   * <pre>
   * Whether or not Mux is enabled.
   * </pre>
   *
   * <code>bool enabled = 1;</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int CONCURRENCY_FIELD_NUMBER = 2;
  private int concurrency_ = 0;
  /**
   * <pre>
   * Max number of concurrent connections that one Mux connection can handle.
   * </pre>
   *
   * <code>int32 concurrency = 2;</code>
   * @return The concurrency.
   */
  @java.lang.Override
  public int getConcurrency() {
    return concurrency_;
  }

  public static final int XUDPCONCURRENCY_FIELD_NUMBER = 3;
  private int xudpConcurrency_ = 0;
  /**
   * <pre>
   * Transport XUDP in another Mux.
   * </pre>
   *
   * <code>int32 xudpConcurrency = 3;</code>
   * @return The xudpConcurrency.
   */
  @java.lang.Override
  public int getXudpConcurrency() {
    return xudpConcurrency_;
  }

  public static final int XUDPPROXYUDP443_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object xudpProxyUDP443_ = "";
  /**
   * <pre>
   * "reject" (default), "allow" or "skip".
   * </pre>
   *
   * <code>string xudpProxyUDP443 = 4;</code>
   * @return The xudpProxyUDP443.
   */
  @java.lang.Override
  public java.lang.String getXudpProxyUDP443() {
    java.lang.Object ref = xudpProxyUDP443_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xudpProxyUDP443_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "reject" (default), "allow" or "skip".
   * </pre>
   *
   * <code>string xudpProxyUDP443 = 4;</code>
   * @return The bytes for xudpProxyUDP443.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getXudpProxyUDP443Bytes() {
    java.lang.Object ref = xudpProxyUDP443_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xudpProxyUDP443_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enabled_ != false) {
      output.writeBool(1, enabled_);
    }
    if (concurrency_ != 0) {
      output.writeInt32(2, concurrency_);
    }
    if (xudpConcurrency_ != 0) {
      output.writeInt32(3, xudpConcurrency_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(xudpProxyUDP443_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, xudpProxyUDP443_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enabled_);
    }
    if (concurrency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, concurrency_);
    }
    if (xudpConcurrency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, xudpConcurrency_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(xudpProxyUDP443_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, xudpProxyUDP443_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.paolu.xray.app.proxyman.MultiplexingConfig)) {
      return super.equals(obj);
    }
    cloud.paolu.xray.app.proxyman.MultiplexingConfig other = (cloud.paolu.xray.app.proxyman.MultiplexingConfig) obj;

    if (getEnabled()
        != other.getEnabled()) return false;
    if (getConcurrency()
        != other.getConcurrency()) return false;
    if (getXudpConcurrency()
        != other.getXudpConcurrency()) return false;
    if (!getXudpProxyUDP443()
        .equals(other.getXudpProxyUDP443())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    hash = (37 * hash) + CONCURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getConcurrency();
    hash = (37 * hash) + XUDPCONCURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getXudpConcurrency();
    hash = (37 * hash) + XUDPPROXYUDP443_FIELD_NUMBER;
    hash = (53 * hash) + getXudpProxyUDP443().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.paolu.xray.app.proxyman.MultiplexingConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xray.app.proxyman.MultiplexingConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xray.app.proxyman.MultiplexingConfig)
      cloud.paolu.xray.app.proxyman.MultiplexingConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.paolu.xray.app.proxyman.Config.internal_static_xray_app_proxyman_MultiplexingConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.paolu.xray.app.proxyman.Config.internal_static_xray_app_proxyman_MultiplexingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.paolu.xray.app.proxyman.MultiplexingConfig.class, cloud.paolu.xray.app.proxyman.MultiplexingConfig.Builder.class);
    }

    // Construct using cloud.paolu.xray.app.proxyman.MultiplexingConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      enabled_ = false;
      concurrency_ = 0;
      xudpConcurrency_ = 0;
      xudpProxyUDP443_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.paolu.xray.app.proxyman.Config.internal_static_xray_app_proxyman_MultiplexingConfig_descriptor;
    }

    @java.lang.Override
    public cloud.paolu.xray.app.proxyman.MultiplexingConfig getDefaultInstanceForType() {
      return cloud.paolu.xray.app.proxyman.MultiplexingConfig.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.paolu.xray.app.proxyman.MultiplexingConfig build() {
      cloud.paolu.xray.app.proxyman.MultiplexingConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.paolu.xray.app.proxyman.MultiplexingConfig buildPartial() {
      cloud.paolu.xray.app.proxyman.MultiplexingConfig result = new cloud.paolu.xray.app.proxyman.MultiplexingConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.paolu.xray.app.proxyman.MultiplexingConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.enabled_ = enabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.concurrency_ = concurrency_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.xudpConcurrency_ = xudpConcurrency_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.xudpProxyUDP443_ = xudpProxyUDP443_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.paolu.xray.app.proxyman.MultiplexingConfig) {
        return mergeFrom((cloud.paolu.xray.app.proxyman.MultiplexingConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.paolu.xray.app.proxyman.MultiplexingConfig other) {
      if (other == cloud.paolu.xray.app.proxyman.MultiplexingConfig.getDefaultInstance()) return this;
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (other.getConcurrency() != 0) {
        setConcurrency(other.getConcurrency());
      }
      if (other.getXudpConcurrency() != 0) {
        setXudpConcurrency(other.getXudpConcurrency());
      }
      if (!other.getXudpProxyUDP443().isEmpty()) {
        xudpProxyUDP443_ = other.xudpProxyUDP443_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              enabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              concurrency_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              xudpConcurrency_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              xudpProxyUDP443_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean enabled_ ;
    /**
     * <pre>
     * Whether or not Mux is enabled.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <pre>
     * Whether or not Mux is enabled.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {

      enabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether or not Mux is enabled.
     * </pre>
     *
     * <code>bool enabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      enabled_ = false;
      onChanged();
      return this;
    }

    private int concurrency_ ;
    /**
     * <pre>
     * Max number of concurrent connections that one Mux connection can handle.
     * </pre>
     *
     * <code>int32 concurrency = 2;</code>
     * @return The concurrency.
     */
    @java.lang.Override
    public int getConcurrency() {
      return concurrency_;
    }
    /**
     * <pre>
     * Max number of concurrent connections that one Mux connection can handle.
     * </pre>
     *
     * <code>int32 concurrency = 2;</code>
     * @param value The concurrency to set.
     * @return This builder for chaining.
     */
    public Builder setConcurrency(int value) {

      concurrency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Max number of concurrent connections that one Mux connection can handle.
     * </pre>
     *
     * <code>int32 concurrency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConcurrency() {
      bitField0_ = (bitField0_ & ~0x00000002);
      concurrency_ = 0;
      onChanged();
      return this;
    }

    private int xudpConcurrency_ ;
    /**
     * <pre>
     * Transport XUDP in another Mux.
     * </pre>
     *
     * <code>int32 xudpConcurrency = 3;</code>
     * @return The xudpConcurrency.
     */
    @java.lang.Override
    public int getXudpConcurrency() {
      return xudpConcurrency_;
    }
    /**
     * <pre>
     * Transport XUDP in another Mux.
     * </pre>
     *
     * <code>int32 xudpConcurrency = 3;</code>
     * @param value The xudpConcurrency to set.
     * @return This builder for chaining.
     */
    public Builder setXudpConcurrency(int value) {

      xudpConcurrency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport XUDP in another Mux.
     * </pre>
     *
     * <code>int32 xudpConcurrency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearXudpConcurrency() {
      bitField0_ = (bitField0_ & ~0x00000004);
      xudpConcurrency_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object xudpProxyUDP443_ = "";
    /**
     * <pre>
     * "reject" (default), "allow" or "skip".
     * </pre>
     *
     * <code>string xudpProxyUDP443 = 4;</code>
     * @return The xudpProxyUDP443.
     */
    public java.lang.String getXudpProxyUDP443() {
      java.lang.Object ref = xudpProxyUDP443_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xudpProxyUDP443_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "reject" (default), "allow" or "skip".
     * </pre>
     *
     * <code>string xudpProxyUDP443 = 4;</code>
     * @return The bytes for xudpProxyUDP443.
     */
    public com.google.protobuf.ByteString
        getXudpProxyUDP443Bytes() {
      java.lang.Object ref = xudpProxyUDP443_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xudpProxyUDP443_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "reject" (default), "allow" or "skip".
     * </pre>
     *
     * <code>string xudpProxyUDP443 = 4;</code>
     * @param value The xudpProxyUDP443 to set.
     * @return This builder for chaining.
     */
    public Builder setXudpProxyUDP443(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      xudpProxyUDP443_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "reject" (default), "allow" or "skip".
     * </pre>
     *
     * <code>string xudpProxyUDP443 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearXudpProxyUDP443() {
      xudpProxyUDP443_ = getDefaultInstance().getXudpProxyUDP443();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "reject" (default), "allow" or "skip".
     * </pre>
     *
     * <code>string xudpProxyUDP443 = 4;</code>
     * @param value The bytes for xudpProxyUDP443 to set.
     * @return This builder for chaining.
     */
    public Builder setXudpProxyUDP443Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      xudpProxyUDP443_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xray.app.proxyman.MultiplexingConfig)
  }

  // @@protoc_insertion_point(class_scope:xray.app.proxyman.MultiplexingConfig)
  private static final cloud.paolu.xray.app.proxyman.MultiplexingConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.paolu.xray.app.proxyman.MultiplexingConfig();
  }

  public static cloud.paolu.xray.app.proxyman.MultiplexingConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiplexingConfig>
      PARSER = new com.google.protobuf.AbstractParser<MultiplexingConfig>() {
    @java.lang.Override
    public MultiplexingConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MultiplexingConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultiplexingConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.paolu.xray.app.proxyman.MultiplexingConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

