// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/config.proto

package cloud.paolu.xray.app.proxyman;

public interface OutboundConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xray.app.proxyman.OutboundConfig)
    com.google.protobuf.MessageOrBuilder {
}
